// src/app/modules/editor/components/layertimeline/TimelineAnimationRow.tsx
import { useAppSelector } from 'app/modules/editor/hooks/useAppSelector';
import type { Layer } from 'app/modules/editor/model/layers';
import * as ModelUtil from 'app/modules/editor/scripts/common/ModelUtil';
import { getTimelineAnimationRowState } from 'app/modules/editor/store/common/selectors';
import _ from 'lodash';
import { memo, useMemo } from 'react';

import { useLayerTimelineController } from './LayerTimelineContext';
import './timelineanimationrow.scss';

/**
 * Shows the layer's animation blocks, and (recursively) those of its children.
 */
export const TimelineAnimationRow = memo(function TimelineAnimationRow({
  layer,
}: {
  layer: Layer;
}) {
  const controller = useLayerTimelineController();
  const { animation, collapsedLayerIds, selectedBlockIds, isActionMode } = useAppSelector(
    getTimelineAnimationRowState,
  );
  // A list of animation block lists. Each animation block list corresponds to
  // a property name displayed in the layer list tree.
  const blocksByPropertyNameValues = useMemo(
    () => _.values(ModelUtil.getOrderedBlocksByPropertyByLayer(animation)[layer.id]),
    [animation, layer.id],
  );
  const isExpanded = !collapsedLayerIds.has(layer.id);

  return (
    <div className="app-timelineanimationrow">
      <div className="slt-layer-row" />
      {isExpanded && (
        <div
          className={`slt-properties${blocksByPropertyNameValues.length ? '' : ' slt-properties-empty'}`}
        >
          {blocksByPropertyNameValues.map(blocks => (
            <div className="slt-property" key={blocks[0].propertyName}>
              {blocks.map(block => {
                const isSelected = selectedBlockIds.has(block.id);
                const isAnimatable = block.isAnimatable();
                const classNames = [
                  'slt-timeline-block',
                  isActionMode && 'is-disabled',
                  isAnimatable && isSelected && 'is-selected',
                  !isAnimatable && !isSelected && 'has-error',
                  !isAnimatable && isSelected && 'is-selected-with-error',
                ];
                return (
                  <div
                    key={block.id}
                    className={classNames.filter(Boolean).join(' ')}
                    tabIndex={-1}
                    style={{
                      left: `${(100 * block.startTime) / animation.duration}%`,
                      width: `${(100 * (block.endTime - block.startTime)) / animation.duration}%`,
                    }}
                    onClick={event => {
                      event.stopPropagation();
                      if (!isActionMode) {
                        controller.onTimelineBlockClick(event.nativeEvent, block);
                      }
                    }}
                    onDoubleClick={event => {
                      event.stopPropagation();
                      if (!isActionMode) {
                        controller.onTimelineBlockDoubleClick(event.nativeEvent, block);
                      }
                    }}
                    onMouseDown={event => {
                      if (!isActionMode) {
                        controller.onTimelineBlockMouseDown(event.nativeEvent, block);
                      }
                    }}
                  >
                    <div className="slt-timeline-block-edge slt-timeline-block-edge-start" />
                    <div className="slt-timeline-block-edge slt-timeline-block-edge-end" />
                  </div>
                );
              })}
            </div>
          ))}
        </div>
      )}
      {isExpanded && layer.children.length > 0 && (
        <ul className="slt-children-row">
          {layer.children.map(child => (
            <li key={child.id}>
              <TimelineAnimationRow layer={child} />
            </li>
          ))}
        </ul>
      )}
    </div>
  );
});

// src/app/layertimeline/timelineanimationrow.component.ts
import { AnimationMap, ModelUtil } from '../scripts/common';
import { Layer } from '../scripts/layers';
import { Animation, AnimationBlock } from '../scripts/timeline';
import { State, Store } from '../store';
import { getTimelineAnimationRowState } from '../store/common/selectors';
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  OnInit,
  Output,
  ViewEncapsulation,
} from '@angular/core';
import * as _ from 'lodash';
import { Observable } from 'rxjs/Observable';

@Component({
  selector: 'app-timelineanimationrow',
  templateUrl: './timelineanimationrow.component.html',
  styleUrls: ['./timelineanimationrow.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
  // TODO: remove ViewEncapsulation.
  encapsulation: ViewEncapsulation.None,
})
export class TimelineAnimationRowComponent implements OnInit, Callbacks {

  animationRowModel$: Observable<AnimationRowModel>;

  @Input() layer: Layer;
  @Input() animation: Layer;

  // MouseEvents from this layer (or children layers further down the tree)
  // are recursively handled by parent components until they reach
  // the LayerTimelineComponent.
  @Output() onTimelineBlockClick = new EventEmitter<Event>();
  @Output() onTimelineBlockMouseDown = new EventEmitter<Event>();

  constructor(private readonly store: Store<State>) { }

  ngOnInit() {
    this.animationRowModel$ =
      this.store.select(getTimelineAnimationRowState)
        .map(({ animations, collapsedLayerIds, selectedBlockIds }) => {
          const blocksByAnimationByPropertyValues =
            _.values(ModelUtil.getBlocksByAnimationByProperty(this.layer.id, animations));
          console.info(blocksByAnimationByPropertyValues);
          return {
            blocksByAnimationByPropertyValues,
            isExpanded: !collapsedLayerIds.has(this.layer.id),
            selectedBlockIds,
          }
        })
  }

  // @Override Callbacks
  timelineBlockClick(
    event: MouseEvent,
    block: AnimationBlock,
    animation: Animation,
    layer: Layer,
  ) {
    console.info(block, block.isAnimatable());
    this.onTimelineBlockClick.emit({ event, block, animation, layer });
  }

  // @Override Callbacks
  timelineBlockMouseDown(
    event: MouseEvent,
    block: AnimationBlock,
    animation: Animation,
    layer: Layer,
  ) {
    this.onTimelineBlockMouseDown.emit({ event, block, animation, layer });
  }

  // Used by *ngFor loop.
  trackLayerFn(index: number, layer: Layer) {
    return layer.id;
  }
}

export interface Callbacks {
  timelineBlockMouseDown(
    event: MouseEvent,
    block: AnimationBlock,
    animation: Animation,
    layer: Layer,
  );
  timelineBlockClick(
    event: MouseEvent,
    block: AnimationBlock,
    animation: Animation,
    layer: Layer,
  );
}

interface AnimationRowModel {
  readonly blocksByAnimationByPropertyValues: AnimationMap<AnimationBlock[]>[];
  readonly isExpanded: boolean;
  readonly selectedBlockIds: Set<string>;
}

interface Event {
  readonly event: MouseEvent;
  readonly block: AnimationBlock;
  readonly animation: Animation;
  readonly layer: Layer;
}

<!-- TODO: conflicts with other scss files causes pointer to be displayed for empty rows -->
<div class="slt-layer slt-layer-type-{{ this.layer.getType() }}"></div>

<ng-container *ngIf="(this.animationRowModel$ | async) as model">
  <div class="slt-properties"
    *ngIf="model.isExpanded"
    [ngClass]="{'slt-properties-empty': !model.blocksByAnimationByPropertyValues.length}">
    <div class="slt-property"
      *ngFor="let blocksByAnimation of model.blocksByAnimationByPropertyValues">
      <!-- TODO: highlight selected animation blocks HERE! -->
      <div class="slt-timeline-block"
        *ngFor="let block of blocksByAnimation[this.animation.id]"
        (click)="this.timelineBlockClick($event, block, this.animation, this.layer)"
        (mousedown)="this.timelineBlockMouseDown($event, block, this.animation, this.layer)"
        tabindex="-1"
        [ngStyle]="{
          'left': (100 * block.startTime / this.animation.duration) + '%',
          'width': (100 * (block.endTime - block.startTime) / this.animation.duration) + '%'
        }"
        [ngClass]="{'is-selected': false}">
        <div class="slt-timeline-block-edge slt-timeline-block-edge-start"></div>
        <div class="slt-timeline-block-edge slt-timeline-block-edge-end"></div>
      </div>
    </div>
  </div>

  <ul class="slt-children"
    *ngIf="layer.children.length > 0 && model.isExpanded">
    <li *ngFor="let child of layer.children">
      <app-timelineanimationrow [layer]="child"
        [animation]="this.animation"
        (onTimelineBlockMouseDown)="this.timelineBlockMouseDown($event.event, $event.block, $event.animation, $event.layer)"
        (onTimelineBlockClick)="this.timelineBlockClick($event.event, $event.block, $event.animation, $event.layer)">
      </app-timelineanimationrow>
    </li>
  </ul>
</ng-container>
