// src/app/modules/editor/components/toolbar/toolbar.component.ts
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';
import {
  ActionMode,
  ActionSource,
  Selection,
  SelectionType,
} from 'app/modules/editor/model/actionmode';
import { MorphableLayer } from 'app/modules/editor/model/layers';
import { PathAnimationBlock } from 'app/modules/editor/model/timeline';
import { ActionModeUtil } from 'app/modules/editor/scripts/actionmode';
import { ActionModeService, ThemeService } from 'app/modules/editor/services';
import { State, Store } from 'app/modules/editor/store';
import { getToolbarState } from 'app/modules/editor/store/actionmode/selectors';
import { ThemeType } from 'app/modules/editor/store/theme/reducer';
import * as _ from 'lodash';
import { Observable, combineLatest } from 'rxjs';
import { map } from 'rxjs/operators';

declare const ga: Function;

@Component({
  selector: 'app-toolbar',
  templateUrl: './toolbar.component.html',
  styleUrls: ['./toolbar.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ToolbarComponent implements OnInit {
  toolbarData$: Observable<ToolbarData>;
  themeState$: Observable<{
    prevThemeType: ThemeType;
    currThemeType: ThemeType;
    prevIsActionMode: boolean;
    currIsActionMode: boolean;
  }>;

  constructor(
    private readonly actionModeService: ActionModeService,
    readonly themeService: ThemeService,
    private readonly store: Store<State>,
  ) {}

  ngOnInit() {
    let hasActionModeBeenEnabled = false;
    let prevThemeType: ThemeType;
    let currThemeType = this.themeService.getThemeType().themeType;
    let prevIsActionMode: boolean;
    let currIsActionMode = this.actionModeService.getActionMode() !== ActionMode.None;
    const toolbarState = this.store.select(getToolbarState);
    this.toolbarData$ = toolbarState.pipe(
      map(({ mode, fromMl, toMl, selections, unpairedSubPath, block }) => {
        return new ToolbarData(mode, fromMl, toMl, selections, unpairedSubPath, block);
      }),
    );
    this.themeState$ = combineLatest(
      toolbarState,
      this.themeService.asObservable().pipe(map(t => t.themeType)),
    ).pipe(
      map(([{ mode }, themeType]) => {
        hasActionModeBeenEnabled = hasActionModeBeenEnabled || mode !== ActionMode.None;
        prevThemeType = currThemeType;
        currThemeType = themeType;
        prevIsActionMode = currIsActionMode;
        currIsActionMode = mode !== ActionMode.None;
        return {
          hasActionModeBeenEnabled,
          prevThemeType,
          currThemeType,
          prevIsActionMode,
          currIsActionMode,
        };
      }),
    );
  }

  get darkTheme() {
    return this.themeService.getThemeType().themeType === 'dark';
  }

  set darkTheme(isDark: boolean) {
    this.themeService.setTheme(isDark ? 'dark' : 'light');
  }

  onSendFeedbackClick(event: MouseEvent) {
    ga('send', 'event', 'Miscellaneous', 'Send feedback click');
  }

  onContributeClick(event: MouseEvent) {
    ga('send', 'event', 'Miscellaneous', 'Contribute click');
  }

  onGettingStartedClick(event: MouseEvent) {
    ga('send', 'event', 'Miscellaneous', 'Getting started click');
  }

  onAutoFixClick(event: MouseEvent) {
    ga('send', 'event', 'Action mode', 'Auto fix click');
    event.stopPropagation();
    this.actionModeService.autoFix();
  }

  onCloseActionModeClick(event: MouseEvent) {
    event.stopPropagation();
    this.actionModeService.closeActionMode();
  }

  onAddPointsClick(event: MouseEvent) {
    ga('send', 'event', 'Action mode', 'Add points');
    event.stopPropagation();
    this.actionModeService.toggleSplitCommandsMode();
  }

  onSplitSubPathsClick(event: MouseEvent) {
    ga('send', 'event', 'Action mode', 'Split sub paths');
    event.stopPropagation();
    this.actionModeService.toggleSplitSubPathsMode();
  }

  onPairSubPathsClick(event: MouseEvent) {
    ga('send', 'event', 'Action mode', 'Pair sub paths');
    event.stopPropagation();
    this.actionModeService.togglePairSubPathsMode();
  }

  onReversePointsClick(event: MouseEvent) {
    event.stopPropagation();
    this.actionModeService.reverseSelectedSubPaths();
  }

  onShiftBackPointsClick(event: MouseEvent) {
    event.stopPropagation();
    this.actionModeService.shiftBackSelectedSubPaths();
  }

  onShiftForwardPointsClick(event: MouseEvent) {
    event.stopPropagation();
    this.actionModeService.shiftForwardSelectedSubPaths();
  }

  onDeleteSubPathsClick(event: MouseEvent) {
    event.stopPropagation();
    this.actionModeService.deleteSelectedActionModeModels();
  }

  onDeleteSegmentsClick(event: MouseEvent) {
    event.stopPropagation();
    this.actionModeService.deleteSelectedActionModeModels();
  }

  onSetFirstPositionClick(event: MouseEvent) {
    event.stopPropagation();
    this.actionModeService.shiftPointToFront();
  }

  onSplitInHalfHoverEvent(isHovering: boolean) {
    if (isHovering) {
      this.actionModeService.splitInHalfHover();
    } else {
      this.actionModeService.clearHover();
    }
  }

  onSplitInHalfClick(event: MouseEvent) {
    event.stopPropagation();
    this.actionModeService.splitSelectedPointInHalf();
  }

  onDeletePointsClick(event: MouseEvent) {
    event.stopPropagation();
    this.actionModeService.deleteSelectedActionModeModels();
  }
}

class ToolbarData {
  private readonly subPaths: ReadonlyArray<number> = [];
  private readonly segments: ReadonlyArray<{ subIdx: number; cmdIdx: number }> = [];
  private readonly points: ReadonlyArray<{ subIdx: number; cmdIdx: number }> = [];
  private readonly numSplitSubPaths: number;
  private readonly numSplitPoints: number;
  private readonly showSetFirstPosition: boolean;
  private readonly showShiftSubPath: boolean;
  private readonly isFilled: boolean;
  private readonly isStroked: boolean;
  private readonly showSplitInHalf: boolean;
  private readonly unpairedSubPathSource: ActionSource;
  private readonly showPairSubPaths: boolean;

  constructor(
    readonly mode: ActionMode,
    startMorphableLayer: MorphableLayer,
    endMorphableLayer: MorphableLayer,
    readonly selections: ReadonlyArray<Selection>,
    unpair: { source: ActionSource; subIdx: number },
    private readonly block: PathAnimationBlock | undefined,
  ) {
    // Precondition: assume all selections are for the same canvas type
    if (!selections.length) {
      return;
    }
    const canvasType = selections[0].source;
    const morphableLayer =
      canvasType === ActionSource.From ? startMorphableLayer : endMorphableLayer;
    if (!morphableLayer) {
      return;
    }
    const activePath = morphableLayer.pathData;
    this.isFilled = morphableLayer.isFilled();
    this.isStroked = morphableLayer.isStroked();
    this.subPaths = selections.filter(s => s.type === SelectionType.SubPath).map(s => s.subIdx);
    this.segments = selections
      .filter(s => {
        const { subIdx, cmdIdx } = s;
        return (
          s.type === SelectionType.Segment &&
          morphableLayer.isFilled() &&
          activePath.getCommand(subIdx, cmdIdx).isSplitSegment()
        );
      })
      .map(s => {
        const { subIdx, cmdIdx } = s;
        return { subIdx, cmdIdx };
      });
    this.points = selections.filter(s => s.type === SelectionType.Point).map(s => {
      const { subIdx, cmdIdx } = s;
      return { subIdx, cmdIdx };
    });

    this.numSplitSubPaths = _.sumBy(this.subPaths, subIdx => {
      return activePath.getSubPath(subIdx).isUnsplittable() ? 1 : 0;
    });
    this.numSplitPoints = _.sumBy(this.points, s => {
      const { subIdx, cmdIdx } = s;
      return activePath.getCommand(subIdx, cmdIdx).isSplitPoint() ? 1 : 0;
    });
    this.showSetFirstPosition =
      this.points.length === 1 &&
      this.points[0].cmdIdx &&
      activePath.getSubPath(this.points[0].subIdx).isClosed();
    this.showShiftSubPath =
      this.subPaths.length > 0 && activePath.getSubPath(this.subPaths[0]).isClosed();
    this.showSplitInHalf = this.points.length === 1 && !!this.points[0].cmdIdx;
    if (this.mode === ActionMode.PairSubPaths) {
      if (unpair) {
        this.unpairedSubPathSource = unpair.source;
      }
    }
    this.showPairSubPaths =
      startMorphableLayer.pathData.getSubPaths().length === 1 &&
      endMorphableLayer.pathData.getSubPaths().length === 1
        ? false
        : this.getNumSubPaths() === 1 || this.getNumSegments() > 0 || !this.isSelectionMode();
  }

  getNumSelections() {
    return this.subPaths.length + this.segments.length + this.points.length;
  }

  getNumSubPaths() {
    return this.subPaths.length;
  }

  getNumSegments() {
    return this.segments.length;
  }

  getNumPoints() {
    return this.points.length;
  }

  getToolbarTitle() {
    if (this.mode === ActionMode.SplitCommands) {
      return 'Add points';
    }
    if (this.mode === ActionMode.SplitSubPaths) {
      return 'Split subpaths';
    }
    if (this.mode === ActionMode.PairSubPaths) {
      return 'Pair subpaths';
    }
    const numSubPaths = this.getNumSubPaths();
    const subStr = `${numSubPaths} subpath${numSubPaths === 1 ? '' : 's'}`;
    const numSegments = this.getNumSegments();
    const segStr = `${numSegments} segment${numSegments === 1 ? '' : 's'}`;
    const numPoints = this.getNumPoints();
    const ptStr = `${numPoints} point${numPoints === 1 ? '' : 's'}`;
    if (numSubPaths > 0) {
      return `${subStr} selected`;
    } else if (numSegments > 0) {
      return `${segStr} selected`;
    } else if (numPoints > 0) {
      return `${ptStr} selected`;
    } else if (this.mode === ActionMode.Selection) {
      return 'Edit path morphing animation';
    }
    return 'Shape Shifter';
  }

  getToolbarSubtitle() {
    if (this.mode === ActionMode.SplitCommands) {
      return 'Click along the edge of a subpath to add a point';
    } else if (this.mode === ActionMode.SplitSubPaths) {
      if (this.isFilled) {
        return 'Draw a line across a subpath to split it into 2';
      } else if (this.isStroked) {
        return 'Click along the edge of a subpath to split it into 2';
      }
    } else if (this.mode === ActionMode.PairSubPaths) {
      if (this.unpairedSubPathSource) {
        const toSourceDir = this.unpairedSubPathSource === ActionSource.From ? 'right' : 'left';
        return `Pair the selected subpath with a corresponding subpath on the ${toSourceDir}`;
      }
      return 'Select a subpath';
    } else if (this.mode === ActionMode.Selection) {
      const { areCompatible, errorPath, numPointsMissing } = ActionModeUtil.checkPathsCompatible(
        this.block,
      );
      if (!areCompatible) {
        const createSubtitleFn = (direction: string) => {
          if (numPointsMissing === 1) {
            return `Add 1 point to the highlighted subpath on the ${direction}`;
          } else {
            return `Add ${numPointsMissing} points to the highlighted subpath on the ${direction}`;
          }
        };
        if (errorPath === ActionSource.From) {
          return createSubtitleFn('left');
        } else if (errorPath === ActionSource.To) {
          return createSubtitleFn('right');
        }
        // This should never happen, but return empty string just to be safe.
        return '';
      }
      if (!this.getNumSubPaths() && !this.getNumSegments() && !this.getNumPoints()) {
        return 'Select something below to edit its properties';
      }
    }
    return '';
  }

  shouldShowActionMode() {
    return this.mode !== ActionMode.None;
  }

  shouldShowPairSubPaths() {
    return this.showPairSubPaths;
  }

  getNumSplitSubPaths() {
    return this.numSplitSubPaths || 0;
  }

  getNumSplitPoints() {
    return this.numSplitPoints || 0;
  }

  shouldShowSetFirstPosition() {
    return this.showSetFirstPosition || false;
  }

  shouldShowShiftSubPath() {
    return this.showShiftSubPath || false;
  }

  shouldShowSplitInHalf() {
    return this.showSplitInHalf || false;
  }

  isSelectionMode() {
    return this.mode === ActionMode.None || this.mode === ActionMode.Selection;
  }

  isAddPointsMode() {
    return this.mode === ActionMode.SplitCommands;
  }

  isSplitSubPathsMode() {
    return this.mode === ActionMode.SplitSubPaths;
  }

  isPairSubPathsMode() {
    return this.mode === ActionMode.PairSubPaths;
  }

  shouldShowAutoFix() {
    return this.mode === ActionMode.Selection && !this.getNumSelections();
  }
}

<ng-container *ngIf="(this.toolbarData$ | async) as toolbarData">
  <div fxLayout="row"
    fxLayoutAlign="center center"
    *ngIf="(this.themeState$ | async) as state"
    [class.dark-to-light-primary]="state.prevThemeType === 'dark' && state.currThemeType === 'light' && !state.currIsActionMode"

    [class.light-to-dark-primary]="state.prevThemeType === 'light' && state.currThemeType === 'dark' && !state.currIsActionMode"

    [class.dark-to-light-accent]="state.prevThemeType === 'dark' && state.currThemeType === 'light' && state.currIsActionMode"

    [class.light-to-dark-accent]="state.prevThemeType === 'light' && state.currThemeType === 'dark' && state.currIsActionMode"

    [class.action-mode-on-to-off-dark]="state.hasActionModeBeenEnabled && !state.currIsActionMode && state.currThemeType === 'dark'"

    [class.action-mode-off-to-on-dark]="state.currIsActionMode && state.currThemeType === 'dark'"
    [class.action-mode-on-to-off-light]="state.hasActionModeBeenEnabled && !state.currIsActionMode && state.currThemeType === 'light'"

    [class.action-mode-off-to-on-light]="state.currIsActionMode && state.currThemeType === 'light'"
    class="toolbar mat-elevation-z2">

    <ng-container *ngIf="{
      showActionMode: toolbarData.shouldShowActionMode(),
      numSubPaths: toolbarData.getNumSubPaths(),
      numSegments: toolbarData.getNumSegments(),
      numPoints: toolbarData.getNumPoints(),
      toolbarTitle: toolbarData.getToolbarTitle(),
      toolbarSubtitle: toolbarData.getToolbarSubtitle(),
      showAddPoints: toolbarData.getNumSubPaths() > 0 || toolbarData.getNumSegments() > 0 || !toolbarData.isSelectionMode(),
      showSplitSubPaths: toolbarData.getNumSubPaths() > 0 || toolbarData.getNumSegments() > 0 || !toolbarData.isSelectionMode(),
      showPairSubPaths: toolbarData.shouldShowPairSubPaths(),
      showReverseSubPaths: toolbarData.getNumSubPaths() === 1,
      showShiftSubPath: toolbarData.shouldShowShiftSubPath(),
      showSetFirstPosition: toolbarData.shouldShowSetFirstPosition(),
      showDeleteSubPaths: toolbarData.getNumSplitSubPaths() > 0,
      showDeleteSegments: toolbarData.getNumSegments() > 0,
      showDeletePoints: toolbarData.getNumSplitPoints() > 0,
      showSplitInHalf: toolbarData.shouldShowSplitInHalf(),
      showAutoFix: toolbarData.shouldShowAutoFix()
    } as data">

      <!-- Shape Shifter logo. -->
      <mat-icon *ngIf="!data.showActionMode"
        class="toolbar-logo"
        svgIcon="shapeshifter">
      </mat-icon>

      <!-- Action mode close button. -->
      <button mat-icon-button
        *ngIf="data.showActionMode"
        class="action-mode-close-icon"
        (click)="onCloseActionModeClick($event)">
        <mat-icon>{{ toolbarData.isSelectionMode() ? 'arrow_back' : 'close' }}</mat-icon>
      </button>

      <!-- Toolbar text. -->
      <div fxLayout="column">
        <span class="toolbar-title">{{ data.toolbarTitle }}</span>
        <span *ngIf="data.toolbarSubtitle"
          class="toolbar-subtitle">
          {{ data.toolbarSubtitle }}
        </span>
      </div>

      <span fxFlex="1 1 auto"></span>

      <button mat-icon-button
        class="toolbar-action-button"
        (click)="onAutoFixClick($event)"
        matTooltip="Auto fix"
        matTooltipShowDelay="500"
        *ngIf="data.showAutoFix"
        matTooltipPosition="below">
        <mat-icon svgIcon="autofix"></mat-icon>
      </button>

      <!-- SubPath mode. -->
      <button mat-icon-button
        class="toolbar-action-button"
        matTooltip="Add points (A)"
        matTooltipPosition="below"
        *ngIf="data.showAddPoints"
        matTooltipShowDelay="500"
        (click)="onAddPointsClick($event)"
        [class.activated]="toolbarData.isAddPointsMode()">
        <mat-icon>add_circle_outline</mat-icon>
      </button>
      <button mat-icon-button
        class="toolbar-action-button"
        matTooltip="Split subpaths (S)"
        matTooltipPosition="below"
        *ngIf="data.showSplitSubPaths"
        matTooltipShowDelay="500"
        (click)="onSplitSubPathsClick($event)"
        [class.activated]="toolbarData.isSplitSubPathsMode()">
        <mat-icon>content_cut</mat-icon>
      </button>
      <button mat-icon-button
        class="toolbar-action-button"
        matTooltip="Pair subpaths (D)"
        matTooltipPosition="below"
        *ngIf="data.showPairSubPaths"
        matTooltipShowDelay="500"
        (click)="onPairSubPathsClick($event)"
        [class.activated]="toolbarData.isPairSubPathsMode()">
        <mat-icon>compare_arrows</mat-icon>
      </button>
      <button mat-icon-button
        class="toolbar-action-button"
        matTooltip="Reverse points (R)"
        matTooltipPosition="below"
        *ngIf="data.showReverseSubPaths"
        matTooltipShowDelay="500"
        (click)="onReversePointsClick($event)"
        [disabled]="!toolbarData.isSelectionMode()">
        <mat-icon svgIcon="reverse"></mat-icon>
      </button>
      <button mat-icon-button
        class="toolbar-action-button"
        matTooltip="Shift back points (B)"
        matTooltipPosition="below"
        *ngIf="data.showShiftSubPath"
        matTooltipShowDelay="500"
        (click)="onShiftBackPointsClick($event)"
        [disabled]="!toolbarData.isSelectionMode()">
        <mat-icon>skip_previous</mat-icon>
      </button>
      <button mat-icon-button
        class="toolbar-action-button"
        matTooltip="Shift forward points (F)"
        matTooltipPosition="below"
        *ngIf="data.showShiftSubPath"
        matTooltipShowDelay="500"
        (click)="onShiftForwardPointsClick($event)"
        [disabled]="!toolbarData.isSelectionMode()">
        <mat-icon>skip_next</mat-icon>
      </button>
      <button mat-icon-button
        class="toolbar-action-button"
        matTooltipPosition="below"
        matTooltip="Delete subpath{{data.numSubPaths === 1 ? '' : 's'}}"
        matTooltipShowDelay="500"
        *ngIf="data.showDeleteSubPaths"
        (click)="onDeleteSubPathsClick($event)">
        <mat-icon>delete</mat-icon>
      </button>

      <!-- Segment mode. -->
      <button mat-icon-button
        class="toolbar-action-button"
        matTooltipPosition="below"
        matTooltip="Delete segment{{data.numSegments === 1 ? '' : 's'}}"
        matTooltipShowDelay="500"
        *ngIf="data.showDeleteSegments"
        (click)="onDeleteSegmentsClick($event)">
        <mat-icon>delete</mat-icon>
      </button>

      <!-- Point mode. -->
      <button mat-icon-button
        matTooltip="Add point (A)"
        matTooltipPosition="below"
        matTooltipShowDelay="500"
        *ngIf="data.showSplitInHalf"
        (mouseenter)="onSplitInHalfHoverEvent(true)"
        (mouseleave)="onSplitInHalfHoverEvent(false)"
        (click)="onSplitInHalfClick($event)">
        <mat-icon>add_circle_outline</mat-icon>
      </button>
      <button mat-icon-button
        class="toolbar-action-button"
        matTooltip="Set first point (F)"
        matTooltipPosition="below"
        matTooltipShowDelay="500"
        *ngIf="data.showSetFirstPosition"
        (click)="onSetFirstPositionClick($event)">
        <mat-icon>looks_one</mat-icon>
      </button>
      <button mat-icon-button
        class="toolbar-action-button"
        matTooltipPosition="below"
        matTooltip="Delete point{{data.numPoints === 1 ? '' : 's'}}"
        matTooltipShowDelay="500"
        *ngIf="data.showDeletePoints"
        (click)="onDeletePointsClick($event)">
        <mat-icon>delete</mat-icon>
      </button>

      <!-- Overflow menu buttons. -->
      <button class="toolbar-action-button"
        mat-icon-button
        (click)="$event.stopPropagation()"
        [matMenuTriggerFor]="overflowMenu">
        <mat-icon>more_vert</mat-icon>
      </button>
      <mat-menu #overflowMenu="matMenu">
        <div mat-menu-item
          (click)="this.darkTheme = !this.darkTheme">
          <mat-slide-toggle (click)="this.darkTheme = !this.darkTheme; $event.stopPropagation()"
            [(ngModel)]="darkTheme"></mat-slide-toggle>
          <span>Dark theme</span>
        </div>
        <a href="http://www.androiddesignpatterns.com/2016/11/introduction-to-icon-animation-techniques.html"
          target="_blank"
          class="toolbar-overflow-link-item">
          <button mat-menu-item
            (click)="this.onGettingStartedClick()">
            <mat-icon>info</mat-icon>
            <span>Getting started</span>
          </button>
        </a>
        <a href="https://github.com/alexjlockwood/ShapeShifter"
          target="_blank"
          class="toolbar-overflow-link-item">
          <button mat-menu-item
            (click)="this.onContributeClick()">
            <mat-icon style="line-height: 1"
              svgIcon="contribute"></mat-icon>
            <span>Contribute</span>
          </button>
        </a>
        <a href="https://github.com/alexjlockwood/ShapeShifter/issues"
          target="_blank"
          class="toolbar-overflow-link-item">
          <button mat-menu-item
            (click)="this.onSendFeedbackClick()">
            <mat-icon>bug_report</mat-icon>
            <span>Send feedback</span>
          </button>
        </a>
        <a href="{{ this.isBeta() ? 'https://shapeshifter.design' : 'https://beta.shapeshifter.design' }}"
          target="_blank"
          class="toolbar-overflow-link-item">
          <button mat-menu-item>
            <mat-icon>open_in_new</mat-icon>
            <span>Switch to {{ this.isBeta() ? 'stable' : 'beta' }} </span>
          </button>
        </a>
      </mat-menu>
    </ng-container>
  </div>
</ng-container>

// src/app/modules/editor/components/toolbar/Toolbar.tsx
import IconButton from '@mui/material/IconButton';
import ListItemIcon from '@mui/material/ListItemIcon';
import ListItemText from '@mui/material/ListItemText';
import Menu from '@mui/material/Menu';
import MenuItem from '@mui/material/MenuItem';
import Switch from '@mui/material/Switch';
import Tooltip from '@mui/material/Tooltip';
import { Tip } from 'app/modules/editor/components/common/Tip';
import { Icon, type IconName } from 'app/modules/editor/components/icons/Icon';
import { useServices } from 'app/modules/editor/context/EditorContext';
import { useAppSelector } from 'app/modules/editor/hooks/useAppSelector';
import { useMenu } from 'app/modules/editor/hooks/useMenu';
import { trackEvent } from 'app/modules/editor/scripts/analytics';
import { getToolbarState } from 'app/modules/editor/store/actionmode/selectors';
import { getThemeType } from 'app/modules/editor/store/theme/selectors';
import { type MouseEvent, useMemo } from 'react';

import './toolbar.scss';
import { ToolbarData } from './ToolbarData';

export function Toolbar() {
  const { actionModeService, themeService } = useServices();
  const toolbarState = useAppSelector(getToolbarState);
  const isDarkTheme = useAppSelector(state => getThemeType(state).themeType === 'dark');
  const overflowMenu = useMenu();

  const toolbarData = useMemo(() => {
    const { mode, fromMl, toMl, selections, unpairedSubPath, block } = toolbarState;
    return new ToolbarData(mode, fromMl, toMl, selections, unpairedSubPath, block);
  }, [toolbarState]);

  const numSubPaths = toolbarData.getNumSubPaths();
  const numSegments = toolbarData.getNumSegments();
  const numPoints = toolbarData.getNumPoints();
  const showActionMode = toolbarData.shouldShowActionMode();
  const toolbarSubtitle = toolbarData.getToolbarSubtitle();
  const showAddPoints = numSubPaths > 0 || numSegments > 0 || !toolbarData.isSelectionMode();
  const showSplitSubPaths = showAddPoints;
  const showShiftSubPath = toolbarData.shouldShowShiftSubPath();

  // Wraps a click handler so that the click isn't also handled by the workspace.
  const onClick = (fn: () => void) => (event: MouseEvent) => {
    event.stopPropagation();
    fn();
  };

  const setDarkTheme = (isDark: boolean) => themeService.setTheme(isDark ? 'dark' : 'light');

  return (
    <div
      className={`toolbar mat-elevation-z2 ss-theme-transition fx-row fx-align-center${
        showActionMode ? ' is-action-mode' : ''
      }`}
    >
      {/* Shape Shifter logo. */}
      {!showActionMode && <Icon className="toolbar-logo" name="shapeshifter" />}

      {/* Action mode close button. */}
      {showActionMode && (
        <IconButton
          className="action-mode-close-icon"
          onClick={onClick(() => actionModeService.closeActionMode())}
        >
          <Icon name={toolbarData.isSelectionMode() ? 'arrow_back' : 'close'} />
        </IconButton>
      )}

      {/* Toolbar text. */}
      <div className="fx-column">
        <span className="toolbar-title">{toolbarData.getToolbarTitle()}</span>
        {toolbarSubtitle && <span className="toolbar-subtitle">{toolbarSubtitle}</span>}
      </div>

      <span className="fx-flex-auto" />

      {toolbarData.shouldShowAutoFix() && (
        <ActionButton
          title="Auto fix"
          icon="autofix"
          onClick={onClick(() => {
            trackEvent('Action mode', 'Auto fix click');
            actionModeService.autoFix();
          })}
        />
      )}

      {/* SubPath mode. */}
      {showAddPoints && (
        <ActionButton
          title="Add points (A)"
          icon="add_circle_outline"
          isActivated={toolbarData.isAddPointsMode()}
          onClick={onClick(() => {
            trackEvent('Action mode', 'Add points');
            actionModeService.toggleSplitCommandsMode();
          })}
        />
      )}
      {showSplitSubPaths && (
        <ActionButton
          title="Split subpaths (S)"
          icon="content_cut"
          isActivated={toolbarData.isSplitSubPathsMode()}
          onClick={onClick(() => {
            trackEvent('Action mode', 'Split sub paths');
            actionModeService.toggleSplitSubPathsMode();
          })}
        />
      )}
      {toolbarData.shouldShowPairSubPaths() && (
        <ActionButton
          title="Pair subpaths (D)"
          icon="compare_arrows"
          isActivated={toolbarData.isPairSubPathsMode()}
          onClick={onClick(() => {
            trackEvent('Action mode', 'Pair sub paths');
            actionModeService.togglePairSubPathsMode();
          })}
        />
      )}
      {numSubPaths === 1 && (
        <ActionButton
          title="Reverse points (R)"
          icon="reverse"
          isDisabled={!toolbarData.isSelectionMode()}
          onClick={onClick(() => actionModeService.reverseSelectedSubPaths())}
        />
      )}
      {showShiftSubPath && (
        <ActionButton
          title="Shift back points (B)"
          icon="skip_previous"
          isDisabled={!toolbarData.isSelectionMode()}
          onClick={onClick(() => actionModeService.shiftBackSelectedSubPaths())}
        />
      )}
      {showShiftSubPath && (
        <ActionButton
          title="Shift forward points (F)"
          icon="skip_next"
          isDisabled={!toolbarData.isSelectionMode()}
          onClick={onClick(() => actionModeService.shiftForwardSelectedSubPaths())}
        />
      )}
      {toolbarData.getNumSplitSubPaths() > 0 && (
        <ActionButton
          title={`Delete subpath${numSubPaths === 1 ? '' : 's'}`}
          icon="delete"
          onClick={onClick(() => actionModeService.deleteSelectedActionModeModels())}
        />
      )}

      {/* Segment mode. */}
      {numSegments > 0 && (
        <ActionButton
          title={`Delete segment${numSegments === 1 ? '' : 's'}`}
          icon="delete"
          onClick={onClick(() => actionModeService.deleteSelectedActionModeModels())}
        />
      )}

      {/* Point mode. */}
      {toolbarData.shouldShowSplitInHalf() && (
        <Tooltip title="Add point (A)">
          <IconButton
            onMouseEnter={() => actionModeService.splitInHalfHover()}
            onMouseLeave={() => actionModeService.clearHover()}
            onClick={onClick(() => actionModeService.splitSelectedPointInHalf())}
          >
            <Icon name="add_circle_outline" />
          </IconButton>
        </Tooltip>
      )}
      {toolbarData.shouldShowSetFirstPosition() && (
        <ActionButton
          title="Set first point (F)"
          icon="looks_one"
          onClick={onClick(() => actionModeService.shiftPointToFront())}
        />
      )}
      {toolbarData.getNumSplitPoints() > 0 && (
        <ActionButton
          title={`Delete point${numPoints === 1 ? '' : 's'}`}
          icon="delete"
          onClick={onClick(() => actionModeService.deleteSelectedActionModeModels())}
        />
      )}

      {/* Overflow menu. */}
      <IconButton
        className="toolbar-action-button"
        aria-label="More options"
        onClick={event => {
          event.stopPropagation();
          overflowMenu.openMenu(event);
        }}
      >
        <Icon name="more_vert" />
      </IconButton>
      <Menu
        className="toolbar-overflow-menu"
        anchorEl={overflowMenu.anchorEl}
        open={overflowMenu.open}
        onClose={overflowMenu.closeMenu}
      >
        <MenuItem
          onClick={() => {
            setDarkTheme(!isDarkTheme);
            overflowMenu.closeMenu();
          }}
        >
          <Switch
            className="toolbar-dark-theme-switch"
            size="small"
            color="secondary"
            checked={isDarkTheme}
            onClick={event => event.stopPropagation()}
            onChange={event => setDarkTheme(event.target.checked)}
          />
          <span>Dark theme</span>
        </MenuItem>
        <OverflowLink
          href="http://www.androiddesignpatterns.com/2016/11/introduction-to-icon-animation-techniques.html"
          icon="info"
          label="Getting started"
          onClick={() => {
            trackEvent('Miscellaneous', 'Getting started click');
            overflowMenu.closeMenu();
          }}
        />
        <OverflowLink
          href="https://github.com/alexjlockwood/ShapeShifter"
          icon="contribute"
          label="Contribute"
          onClick={() => {
            trackEvent('Miscellaneous', 'Contribute click');
            overflowMenu.closeMenu();
          }}
        />
        <OverflowLink
          href="https://github.com/alexjlockwood/ShapeShifter/issues"
          icon="bug_report"
          label="Send feedback"
          onClick={() => {
            trackEvent('Miscellaneous', 'Send feedback click');
            overflowMenu.closeMenu();
          }}
        />
      </Menu>
    </div>
  );
}

interface ActionButtonProps {
  readonly title: string;
  readonly icon: IconName;
  readonly onClick: (event: MouseEvent) => void;
  readonly isActivated?: boolean;
  readonly isDisabled?: boolean;
}

function ActionButton({ title, icon, onClick, isActivated, isDisabled }: ActionButtonProps) {
  const button = (
    <IconButton
      className={`toolbar-action-button${isActivated ? ' activated' : ''}`}
      aria-label={title}
      disabled={isDisabled}
      onClick={onClick}
    >
      <Icon name={icon} />
    </IconButton>
  );
  return (
    <Tip title={title} disabled={isDisabled}>
      {button}
    </Tip>
  );
}

interface OverflowLinkProps {
  readonly href: string;
  readonly icon: IconName;
  readonly label: string;
  readonly onClick: () => void;
}

function OverflowLink({ href, icon, label, onClick }: OverflowLinkProps) {
  return (
    <MenuItem component="a" href={href} target="_blank" rel="noopener" onClick={onClick}>
      <ListItemIcon>
        <Icon name={icon} />
      </ListItemIcon>
      <ListItemText>{label}</ListItemText>
    </MenuItem>
  );
}
