// src/app/modules/editor/components/playback/Playback.tsx
import Fab from '@mui/material/Fab';
import IconButton from '@mui/material/IconButton';
import Tooltip from '@mui/material/Tooltip';
import { Icon } from 'app/modules/editor/components/icons/Icon';
import { useServices } from 'app/modules/editor/context/EditorContext';
import { useAppSelector } from 'app/modules/editor/hooks/useAppSelector';
import { getPlaybackControlsState } from 'app/modules/editor/store/playback/selectors';
import type { MouseEvent } from 'react';

import './playback.scss';

export function Playback() {
  const { playbackService } = useServices();
  const { isSlowMotion, isPlaying, isRepeating } = useAppSelector(getPlaybackControlsState);

  const onClick = (fn: () => void) => (event: MouseEvent) => {
    event.stopPropagation();
    fn();
  };

  return (
    <div className="playback fx-row fx-align-center">
      <span className="fx-flex" />
      <Tooltip title="Slow motion (S)">
        <IconButton
          className="slow-motion-button"
          onClick={onClick(() => playbackService.toggleIsSlowMotion())}
        >
          <Icon name="slow_motion_video" className={isSlowMotion ? 'activated' : undefined} />
        </IconButton>
      </Tooltip>
      <Tooltip title="Rewind (Left)">
        <IconButton onClick={onClick(() => playbackService.rewind())}>
          <Icon name="skip_previous" />
        </IconButton>
      </Tooltip>
      <Tooltip title={`${isPlaying ? 'Pause' : 'Play'} (Spacebar)`}>
        <Fab
          size="small"
          color="secondary"
          onClick={onClick(() => playbackService.toggleIsPlaying())}
        >
          <div className={`play-pause-icon can-animate${isPlaying ? ' is-playing' : ''}`} />
        </Fab>
      </Tooltip>
      <Tooltip title="Fast forward (Right)">
        <IconButton onClick={onClick(() => playbackService.fastForward())}>
          <Icon name="skip_next" />
        </IconButton>
      </Tooltip>
      <Tooltip title="Repeat (R)">
        <IconButton
          className="repeating-button"
          onClick={onClick(() => playbackService.toggleIsRepeating())}
        >
          <Icon name="repeat" className={isRepeating ? 'activated' : undefined} />
        </IconButton>
      </Tooltip>
      <span className="fx-flex" />
    </div>
  );
}

// src/app/components/playback/playback.component.ts
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';
import { PlaybackService } from 'app/services';
import { State, Store } from 'app/store';
import { getPlaybackState } from 'app/store/playback/selectors';
import { Observable } from 'rxjs/Observable';

@Component({
  selector: 'app-playback',
  templateUrl: './playback.component.html',
  styleUrls: ['./playback.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PlaybackComponent implements OnInit {
  playbackModel$: Observable<PlaybackModel>;

  constructor(
    private readonly store: Store<State>,
    private readonly playbackService: PlaybackService,
  ) {}

  ngOnInit() {
    this.playbackModel$ = this.store.select(getPlaybackState);
  }

  isSlowMotionClick(event: MouseEvent) {
    event.stopPropagation();
    this.playbackService.toggleIsSlowMotion();
  }

  rewindClick(event: MouseEvent) {
    event.stopPropagation();
    this.playbackService.rewind();
  }

  playPauseButtonClick(event: MouseEvent) {
    event.stopPropagation();
    this.playbackService.toggleIsPlaying();
  }

  fastForwardClick(event: MouseEvent) {
    event.stopPropagation();
    this.playbackService.fastForward();
  }

  isRepeatingClick(event: MouseEvent) {
    event.stopPropagation();
    this.playbackService.toggleIsRepeating();
  }
}

interface PlaybackModel {
  readonly isSlowMotion: boolean;
  readonly isPlaying: boolean;
  readonly isRepeating: boolean;
}

<div *ngIf="(this.playbackModel$ | async) as model"
  class="playback"
  fxLayout="row"
  fxLayoutAlign="center center">
  <span fxFlex></span>
  <button class="slow-motion-button"
    md-icon-button
    mdTooltip="Slow motion (S)"
    mdTooltipPosition="below"
    mdTooltipShowDelay="500"
    (click)="this.isSlowMotionClick($event)">
    <md-icon [class.activated]="model.isSlowMotion">slow_motion_video</md-icon>
  </button>
  <button md-icon-button
    mdTooltip="Rewind (Left)"
    mdTooltipPosition="below"
    mdTooltipShowDelay="500"
    (click)="this.rewindClick($event)">
    <md-icon>skip_previous</md-icon>
  </button>
  <button md-mini-fab
    mdTooltip="{{ (model.isPlaying) ? 'Pause' : 'Play' }} (Spacebar)"
    mdTooltipPosition="below"
    mdTooltipShowDelay="500"
    (click)="this.playPauseButtonClick($event)">
    <div
      class="play-pause-icon"
      [ngClass]="{
        'can-animate': true,
        'is-playing': model.isPlaying
      }">
    </div>
  </button>
  <button md-icon-button
    mdTooltip="Fast forward (Right)"
    mdTooltipPosition="below"
    mdTooltipShowDelay="500"
    (click)="this.fastForwardClick($event)">
    <md-icon>skip_next</md-icon>
  </button>
  <button class="repeating-button"
    md-icon-button
    mdTooltip="Repeat (R)"
    mdTooltipPosition="below"
    mdTooltipShowDelay="500"
    (click)="this.isRepeatingClick($event)">
    <md-icon [class.activated]="model.isRepeating">repeat</md-icon>
  </button>
  <span fxFlex></span>
</div>
