// src/app/modules/editor/components/layertimeline/TimelineAnimationRow.tsx
import { useAppSelector } from 'app/modules/editor/hooks/useAppSelector';
import type { Layer } from 'app/modules/editor/model/layers';
import * as ModelUtil from 'app/modules/editor/scripts/common/ModelUtil';
import { getTimelineAnimationRowState } from 'app/modules/editor/store/common/selectors';
import _ from 'lodash';
import { memo, useMemo } from 'react';

import { useLayerTimelineController } from './LayerTimelineContext';
import './timelineanimationrow.scss';

/**
 * Shows the layer's animation blocks, and (recursively) those of its children.
 */
export const TimelineAnimationRow = memo(function TimelineAnimationRow({
  layer,
}: {
  layer: Layer;
}) {
  const controller = useLayerTimelineController();
  const { animation, collapsedLayerIds, selectedBlockIds, isActionMode } = useAppSelector(
    getTimelineAnimationRowState,
  );
  // A list of animation block lists. Each animation block list corresponds to
  // a property name displayed in the layer list tree.
  const blocksByPropertyNameValues = useMemo(
    () => _.values(ModelUtil.getOrderedBlocksByPropertyByLayer(animation)[layer.id]),
    [animation, layer.id],
  );
  const isExpanded = !collapsedLayerIds.has(layer.id);

  return (
    <div className="app-timelineanimationrow">
      <div className="slt-layer-row" />
      {isExpanded && (
        <div
          className={`slt-properties${blocksByPropertyNameValues.length ? '' : ' slt-properties-empty'}`}
        >
          {blocksByPropertyNameValues.map(blocks => (
            <div className="slt-property" key={blocks[0].propertyName}>
              {blocks.map(block => {
                const isSelected = selectedBlockIds.has(block.id);
                const isAnimatable = block.isAnimatable();
                const classNames = [
                  'slt-timeline-block',
                  isActionMode && 'is-disabled',
                  isAnimatable && isSelected && 'is-selected',
                  !isAnimatable && !isSelected && 'has-error',
                  !isAnimatable && isSelected && 'is-selected-with-error',
                ];
                return (
                  <div
                    key={block.id}
                    className={classNames.filter(Boolean).join(' ')}
                    tabIndex={-1}
                    style={{
                      left: `${(100 * block.startTime) / animation.duration}%`,
                      width: `${(100 * (block.endTime - block.startTime)) / animation.duration}%`,
                    }}
                    onClick={event => {
                      event.stopPropagation();
                      if (!isActionMode) {
                        controller.onTimelineBlockClick(event.nativeEvent, block);
                      }
                    }}
                    onDoubleClick={event => {
                      event.stopPropagation();
                      if (!isActionMode) {
                        controller.onTimelineBlockDoubleClick(event.nativeEvent, block);
                      }
                    }}
                    onMouseDown={event => {
                      if (!isActionMode) {
                        controller.onTimelineBlockMouseDown(event.nativeEvent, block);
                      }
                    }}
                  >
                    <div className="slt-timeline-block-edge slt-timeline-block-edge-start" />
                    <div className="slt-timeline-block-edge slt-timeline-block-edge-end" />
                  </div>
                );
              })}
            </div>
          ))}
        </div>
      )}
      {isExpanded && layer.children.length > 0 && (
        <ul className="slt-children-row">
          {layer.children.map(child => (
            <li key={child.id}>
              <TimelineAnimationRow layer={child} />
            </li>
          ))}
        </ul>
      )}
    </div>
  );
});

// src/app/components/layertimeline/timelineanimationrow.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  OnInit,
  Output,
} from '@angular/core';
import { ModelUtil } from 'app/scripts/common';
import { Layer } from 'app/scripts/model/layers';
import {
  Animation,
  AnimationBlock,
} from 'app/scripts/model/timeline';
import { ActionModeService } from 'app/services';
import {
  State,
  Store,
} from 'app/store';
import { getTimelineAnimationRowState } from 'app/store/common/selectors';
import * as _ from 'lodash';
import { Observable } from 'rxjs/Observable';

@Component({
  selector: 'app-timelineanimationrow',
  templateUrl: './timelineanimationrow.component.html',
  styleUrls: ['./timelineanimationrow.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class TimelineAnimationRowComponent implements OnInit, Callbacks {

  animationRowModel$: Observable<AnimationRowModel>;

  @Input() layer: Layer;

  // MouseEvents from this layer (or children layers further down the tree)
  // are recursively handled by parent components until they reach
  // the LayerTimelineComponent.
  @Output() onTimelineBlockClick = new EventEmitter<Event>();
  @Output() onTimelineBlockMouseDown = new EventEmitter<Event>();
  @Output() onTimelineBlockDoubleClick = new EventEmitter<Event>();

  constructor(
    private readonly store: Store<State>,
    private readonly actionModeService: ActionModeService,
  ) { }

  ngOnInit() {
    this.animationRowModel$ =
      this.store.select(getTimelineAnimationRowState)
        .map(({ animation, collapsedLayerIds, selectedBlockIds, isActionMode }) => {
          // Returns a list of animation block lists. Each animation block list corresponds to
          // a property name displayed in the layer list tree.
          const blocksByPropertyNameValues =
            _.values(ModelUtil.getOrderedBlocksByPropertyByLayer(animation)[this.layer.id]);
          return {
            animation,
            blocksByPropertyNameValues,
            isExpanded: !collapsedLayerIds.has(this.layer.id),
            selectedBlockIds,
            isActionMode,
          };
        });
  }

  // @Override Callbacks
  timelineBlockClick(event: MouseEvent, block: AnimationBlock) {
    event.stopPropagation();
    if (!this.actionModeService.isActionMode()) {
      this.onTimelineBlockClick.emit({ event, block });
    }
  }

  timelineBlockDoubleClick(event: MouseEvent, block: AnimationBlock) {
    event.stopPropagation();
    if (!this.actionModeService.isActionMode()) {
      this.onTimelineBlockDoubleClick.emit({ event, block });
    }
  }

  // @Override Callbacks
  timelineBlockMouseDown(event: MouseEvent, block: AnimationBlock) {
    if (!this.actionModeService.isActionMode()) {
      this.onTimelineBlockMouseDown.emit({ event, block });
    }
  }

  // Used by *ngFor loop.
  trackLayerFn(index: number, layer: Layer) {
    return layer.id;
  }
}

export interface Callbacks {
  timelineBlockMouseDown(event: MouseEvent, block: AnimationBlock);
  timelineBlockClick(event: MouseEvent, block: AnimationBlock);
  timelineBlockDoubleClick(event: MouseEvent, block: AnimationBlock);
}

interface AnimationRowModel {
  readonly animation: Animation;
  readonly blocksByPropertyNameValues: ReadonlyArray<ReadonlyArray<AnimationBlock>>;
  readonly isExpanded: boolean;
  readonly selectedBlockIds: Set<string>;
  readonly isActionMode: boolean;
}

interface Event {
  readonly event: MouseEvent;
  readonly block: AnimationBlock;
}

<div class="slt-layer-row"></div>

<ng-container *ngIf="(this.animationRowModel$ | async) as model">
  <div class="slt-properties"
    *ngIf="model.isExpanded"
    [ngClass]="{'slt-properties-empty': !model.blocksByPropertyNameValues.length}">
    <div class="slt-property"
      *ngFor="let blocks of model.blocksByPropertyNameValues">
      <div class="slt-timeline-block"
        *ngFor="let block of blocks"
        (dblclick)="this.onTimelineBlockDoubleClick($event, block, this.layer)"
        (click)="this.onTimelineBlockClick($event, block, this.layer)"
        (mousedown)="this.onTimelineBlockMouseDown($event, block, this.layer)"
        tabindex="-1"
        [ngStyle]="{
          'left': (100 * block.startTime / model.animation.duration) + '%',
          'width': (100 * (block.endTime - block.startTime) / model.animation.duration) + '%'
        }"
        [ngClass]="{
          'is-disabled': model.isActionMode,
          'is-selected': block.isAnimatable() && model.selectedBlockIds.has(block.id),
          'has-error': !block.isAnimatable() && !model.selectedBlockIds.has(block.id),
          'is-selected-with-error': !block.isAnimatable() && model.selectedBlockIds.has(block.id)
        }">
        <div class="slt-timeline-block-edge slt-timeline-block-edge-start"></div>
        <div class="slt-timeline-block-edge slt-timeline-block-edge-end"></div>
      </div>
    </div>
  </div>

  <ul class="slt-children-row"
    *ngIf="layer.children.length > 0 && model.isExpanded">
    <li *ngFor="let child of layer.children; trackBy: trackLayerFn">
      <app-timelineanimationrow [layer]="child"
        (timelineBlockMouseDown)="this.onTimelineBlockMouseDown($event.event, $event.block, $event.layer)"
        (timelineBlockClick)="this.onTimelineBlockClick($event.event, $event.block, $event.layer)"
        (timelineBlockDoubleClick)="this.onTimelineBlockDoubleClick($event.event, $event.block, $event.layer)">
      </app-timelineanimationrow>
    </li>
  </ul>
</ng-container>
