// src/app/modules/editor/components/splashscreen/SplashScreen.tsx
import { Icon } from 'app/modules/editor/components/icons/Icon';

import './splashscreen.scss';

export function SplashScreen() {
  return (
    <div className="app-splashscreen fx-column fx-align-center">
      <Icon className="splashscreen-logo" name="shapeshifter" />
      <div className="splashscreen-text">
        Shape Shifter is an icon animation tool designed for desktop browsers
      </div>
    </div>
  );
}

// src/app/components/splashscreen/splashscreen.component.ts
import { ChangeDetectionStrategy, Component } from '@angular/core';

@Component({
  selector: 'app-splashscreen',
  templateUrl: './splashscreen.component.html',
  styleUrls: ['./splashscreen.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class SplashScreenComponent {}

<div fxLayout="column"
  fxLayoutAlign="center center">

  <md-icon class="splashscreen-logo"
    svgIcon="shapeshifter">
  </md-icon>

  <div class="splashscreen-text">Shape Shifter is an icon animation tool designed for desktop browsers</div>

</div>
