// src/app/layertimeline/layerlisttree.component.ts
import { ModelUtil } from '../scripts/common';
import { GroupLayer, Layer, VectorLayer } from '../scripts/layers';
import { Animation } from '../scripts/timeline';
import { State, Store } from '../store';
import { getLayerListTreeState } from '../store/selectors';
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  OnInit,
  Output,
} from '@angular/core';
import * as _ from 'lodash';
import { Observable } from 'rxjs/Observable';

@Component({
  selector: 'app-layerlisttree',
  templateUrl: './layerlisttree.component.html',
  styleUrls: ['./layerlisttree.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LayerListTreeComponent implements OnInit, Callbacks {

  layerModel$: Observable<LayerModel>;

  @Input() layer: Layer;

  // MouseEvents from this layer (or children layers further down the tree)
  // are recursively handled by parent components until they reach
  // the LayerTimelineComponent.
  @Output() onLayerClick = new EventEmitter<LayerEvent>();
  @Output() onLayerDoubleClick = new EventEmitter<LayerEvent>();
  @Output() onLayerMouseDown = new EventEmitter<LayerEvent>();
  @Output() onLayerToggleExpanded = new EventEmitter<LayerEvent>();
  @Output() onLayerToggleVisibility = new EventEmitter<LayerEvent>();
  @Output() onAddTimelineBlockClick = new EventEmitter<TimelineBlockEvent>();

  constructor(private readonly store: Store<State>) { }

  ngOnInit() {
    this.layerModel$ =
      this.store.select(getLayerListTreeState)
        .map(({ animations, selectedLayerIds, collapsedLayerIds, hiddenLayerIds }) => {
          const isExpandable = this.isLayerExpandable();
          const availablePropertyNames =
            Array.from(ModelUtil.getAvailablePropertyNamesForLayer(this.layer, animations));
          const existingPropertyNames =
            Array.from(
              _.keys(ModelUtil.getBlocksByAnimationByProperty(this.layer.id, animations)));
          return {
            animations,
            isSelected: selectedLayerIds.has(this.layer.id),
            isExpandable,
            isExpanded: !collapsedLayerIds.has(this.layer.id),
            isVisible: !hiddenLayerIds.has(this.layer.id),
            availablePropertyNames,
            existingPropertyNames,
          }
        });
  }

  // @Override Callbacks
  layerClick(event: MouseEvent, layer: Layer) {
    this.onLayerClick.emit({ event, layer });
  }

  // @Override Callbacks
  layerMouseDown(event: MouseEvent, layer: Layer) {
    this.onLayerMouseDown.emit({ event, layer });
  }

  // @Override Callbacks
  layerToggleExpanded(event: MouseEvent, layer: Layer) {
    if (this.isLayerExpandable()) {
      this.onLayerToggleExpanded.emit({ event, layer });
    }
    event.stopPropagation();
  }

  // @Override Callbacks
  layerToggleVisibility(event: MouseEvent, layer: Layer) {
    this.onLayerToggleVisibility.emit({ event, layer });
    event.stopPropagation();
  }

  // @Override Callbacks
  addTimelineBlockClick(event: MouseEvent, layer: Layer, propertyName: string) {
    this.onAddTimelineBlockClick.emit({ event, layer, propertyName });
  }

  // Used by *ngFor loop.
  trackLayerFn(index: number, layer: Layer) {
    return layer.id;
  }

  private isLayerExpandable() {
    return this.layer instanceof VectorLayer || this.layer instanceof GroupLayer;
  }
}

export interface Callbacks {
  layerClick(event: MouseEvent, layer: Layer);
  layerMouseDown(event: MouseEvent, layer: Layer);
  layerToggleExpanded(event: MouseEvent, layer: Layer);
  layerToggleVisibility(event: MouseEvent, layer: Layer);
  addTimelineBlockClick(event: MouseEvent, layer: Layer, propertyName: string);
}

interface LayerEvent {
  readonly event: MouseEvent;
  readonly layer: Layer;
}

interface TimelineBlockEvent {
  readonly event: MouseEvent;
  readonly layer: Layer;
  readonly propertyName: string;
}

interface LayerModel {
  readonly animations: ReadonlyArray<Animation>;
  readonly isSelected: boolean;
  readonly isExpandable: boolean;
  readonly isExpanded: boolean;
  readonly isVisible: boolean;
  readonly availablePropertyNames: ReadonlyArray<string>;
  readonly existingPropertyNames: ReadonlyArray<string>;
}

<ng-container *ngIf="(this.layerModel$ | async) as model">
  <div class="slt-layer slt-layer-type-{{ this.layer.getType() }}"
    fxLayout="row"
    fxLayoutAlign="start center"
    [class.is-selected]="model.isSelected"
    (click)="this.layerClick($event, this.layer)"
    (dblclick)="this.layerToggleExpanded($event, this.layer)"
    (mousedown)="this.layerMouseDown($event, this.layer)">
    <button md-icon-button
      *ngIf="model.isExpandable"
      (click)="this.layerToggleExpanded($event, this.layer)"
      mdTooltip="{{model.isExpanded ? 'Collapse layer' : 'Expand layer'}}"
      mdTooltipPosition="below"
      mdTooltipShowDelay="300">
      <md-icon>{{model.isExpanded ? 'expand_more' : 'chevron_right'}}</md-icon>
    </button>
    <!-- Add extra 20px margin if the expand/collapse icon isn't being displayed -->
    <md-icon svgIcon="{{this.layer.getType()}}"
      [style.margin-left]="model.isExpandable ? '0px' : '20px'">
    </md-icon>
    <span class="slt-layer-id-text"
      fxFlex>
      {{this.layer.name}}
    </span>
    <button md-icon-button
      class="slt-layer-action-button slt-layer-more-actions">
      <md-icon>more_vert</md-icon>
    </button>
    <button md-icon-button
      class="slt-layer-action-button slt-layer-visibility-toggle"
      (click)="this.layerToggleVisibility($event, this.layer)"
      mdTooltip="{{model.isVisible ? 'Hide layer' : 'Show layer'}}"
      mdTooltipPosition="below"
      mdTooltipShowDelay="300"
      [ngClass]="{'is-checked': model.isVisible}">
      <md-icon>{{model.isVisible ? 'visibility' : 'visibility_off'}}</md-icon>
    </button>
    <md-menu #addTimelineBlockMenu="mdMenu">
      <button *ngFor="let propertyName of model.availablePropertyNames"
        (click)="this.addTimelineBlockClick($event, layer, propertyName)"
        md-menu-item>
        {{propertyName}}
      </button>
    </md-menu>
    <button md-icon-button
      *ngIf="model.availablePropertyNames.length > 0"
      class="slt-layer-action-button"
      (click)="$event.stopPropagation()"
      mdTooltip="Animate this layer"
      mdTooltipPosition="below"
      mdTooltipShowDelay="300"
      [mdMenuTriggerFor]="addTimelineBlockMenu">
      <md-icon svgIcon="animationblock"></md-icon>
    </button>

  </div>

  <!-- List the property names that have been animated. -->
  <div class="slt-properties"
    *ngIf="model.isExpanded && model.existingPropertyNames.length > 0">
    <div class="slt-property"
      fxLayout="row"
      fxLayoutAlign="start center"
      *ngFor="let propertyName of model.existingPropertyNames">
      <span class="slt-property-name">{{propertyName}}</span>
      <button md-icon-button
        (click)="this.addTimelineBlockClick($event, layer, propertyName)"
        mdTooltip="Add another animation"
        mdTooltipPosition="below"
        mdTooltipShowDelay="300">
        <md-icon>add</md-icon>
      </button>
    </div>
  </div>

  <!-- List the layer's children if it is expanded. -->
  <!-- TODO: will have to remove this attr.data-layer-id stuff -->
  <ul *ngIf="model.isExpanded && this.layer.children.length > 0"
    class="slt-children">
    <li *ngFor="let child of this.layer.children; trackBy: this.trackLayerFn"
      class="slt-layer-container"
      [attr.data-layer-id]="child.id">
      <app-layerlisttree [layer]="child"
        (onLayerClick)="this.layerClick($event.event, $event.layer)"
        (onLayerToggleExpanded)="this.layerToggleExpanded($event.event, $event.layer)"
        (onLayerToggleVisibility)="this.layerToggleVisibility($event.event, $event.layer)"
        (onAddTimelineBlockClick)="this.addTimelineBlockClick($event.event, $event.layer, $event.propertyName)"
        (onLayerMouseDown)="this.layerMouseDown($event.event, $event.layer)">
      </app-layerlisttree>
    </li>
  </ul>
</ng-container>

// src/app/modules/editor/components/layertimeline/LayerListTree.tsx
import IconButton from '@mui/material/IconButton';
import Menu from '@mui/material/Menu';
import MenuItem from '@mui/material/MenuItem';
import { Tip } from 'app/modules/editor/components/common/Tip';
import { Icon, type IconName } from 'app/modules/editor/components/icons/Icon';
import { useAppSelector } from 'app/modules/editor/hooks/useAppSelector';
import { useMenu } from 'app/modules/editor/hooks/useMenu';
import { GroupLayer, type Layer, VectorLayer } from 'app/modules/editor/model/layers';
import { getPropertyTitle } from 'app/modules/editor/model/properties';
import * as ModelUtil from 'app/modules/editor/scripts/common/ModelUtil';
import { ShortcutService } from 'app/modules/editor/services/shortcut.service';
import { getLayerListTreeState } from 'app/modules/editor/store/common/selectors';
import { keys } from 'lodash-es';
import { memo, type MouseEvent, useMemo } from 'react';

import './layerlisttree.scss';
import { useLayerTimelineController } from './LayerTimelineContext';

function buildLayerModel(
  layer: Layer,
  {
    animation,
    selectedLayerIds,
    collapsedLayerIds,
    hiddenLayerIds,
    isActionMode,
  }: ReturnType<typeof getLayerListTreeState>,
) {
  const isExpandable = layer instanceof VectorLayer || layer instanceof GroupLayer;
  const availablePropertyNames = Array.from(
    ModelUtil.getAvailablePropertyNamesForLayer(layer, animation),
  );
  const existingPropertyNames = keys(
    ModelUtil.getOrderedBlocksByPropertyByLayer(animation)[layer.id],
  );
  return {
    isSelected: selectedLayerIds.has(layer.id),
    isExpandable,
    isExpanded: !collapsedLayerIds.has(layer.id),
    isVisible: !hiddenLayerIds.has(layer.id),
    availablePropertyNames,
    existingPropertyNames,
    isActionMode,
  };
}

/**
 * Lists the layer, its animated properties, and (recursively) its children.
 */
export const LayerListTree = memo(function LayerListTree({ layer }: { layer: Layer }) {
  const controller = useLayerTimelineController();
  const layerListTreeState = useAppSelector(getLayerListTreeState);
  const model = useMemo(
    () => buildLayerModel(layer, layerListTreeState),
    [layer, layerListTreeState],
  );
  const addTimelineBlockMenu = useMenu();
  const { isActionMode } = model;

  const onToggleExpanded = (event: MouseEvent) => {
    event.stopPropagation();
    if (model.isExpandable) {
      controller.onLayerToggleExpanded(event.nativeEvent, layer);
    }
  };

  // Stops the click from also selecting the layer.
  const onMenuButtonClick = (openMenu: (event: MouseEvent<HTMLElement>) => void) => {
    return (event: MouseEvent<HTMLElement>) => {
      event.stopPropagation();
      openMenu(event);
    };
  };

  const layerClassNames = [
    'slt-layer',
    `slt-layer-type-${layer.type}`,
    'fx-row',
    'fx-align-start-center',
    model.isSelected && 'is-selected',
    isActionMode && 'is-disabled',
  ];

  return (
    <div className="app-layerlisttree">
      <div
        className={layerClassNames.filter(Boolean).join(' ')}
        onClick={event => {
          event.stopPropagation();
          // On a Mac, a click with Ctrl held is a right-click, which opens the context menu.
          if (!isActionMode && !(ShortcutService.isMac() && event.ctrlKey)) {
            controller.onLayerClick(event.nativeEvent, layer);
          }
        }}
        onDoubleClick={onToggleExpanded}
        onMouseDown={event => {
          if (!isActionMode) {
            controller.onLayerMouseDown(event.nativeEvent, layer);
          }
        }}
        onContextMenu={event => {
          // In action mode, the layers can't be changed, so no menu opens.
          if (!isActionMode) {
            event.preventDefault();
            controller.onLayerContextMenu(layer, { x: event.clientX, y: event.clientY });
          }
        }}
      >
        {model.isExpandable && (
          <Tip
            title={model.isExpanded ? 'Collapse layer' : 'Expand layer'}
            placement="right"
            enterDelay={1000}
            disabled={isActionMode}
          >
            <IconButton disabled={isActionMode} onClick={onToggleExpanded}>
              <Icon name={model.isExpanded ? 'expand_more' : 'chevron_right'} />
            </IconButton>
          </Tip>
        )}
        {/* Add an extra 20px margin if the expand/collapse icon isn't being displayed. */}
        <Icon
          className={model.isExpandable ? 'slt-layer-type-icon' : 'slt-layer-type-icon is-indented'}
          name={layer.type as IconName}
        />
        <span className="slt-layer-id-text fx-flex">{layer.name}</span>
        {/* The context menu, as for a right-click on the layer. */}
        <IconButton
          className="slt-layer-action-button slt-layer-more-actions"
          aria-label="More actions"
          disabled={isActionMode}
          onClick={event => {
            event.stopPropagation();
            const { left, bottom } = event.currentTarget.getBoundingClientRect();
            controller.onLayerContextMenu(layer, { x: left, y: bottom });
          }}
        >
          <Icon name="more_vert" />
        </IconButton>
        {/* Visibility toggle. */}
        <Tip
          title={model.isVisible ? 'Hide layer' : 'Show layer'}
          enterDelay={1000}
          disabled={isActionMode}
        >
          <IconButton
            className={`slt-layer-action-button slt-layer-visibility-toggle${
              model.isVisible ? ' is-checked' : ''
            }`}
            disabled={isActionMode}
            onClick={event => {
              event.stopPropagation();
              if (!isActionMode) {
                controller.onLayerToggleVisibility(layer);
              }
            }}
          >
            <Icon name={model.isVisible ? 'visibility' : 'visibility_off'} />
          </IconButton>
        </Tip>
        {/* Animate layer. */}
        {model.availablePropertyNames.length > 0 && (
          <Tip title="Animate this layer" enterDelay={1000} disabled={isActionMode}>
            <IconButton
              className="slt-layer-action-button"
              disabled={isActionMode}
              onClick={onMenuButtonClick(addTimelineBlockMenu.openMenu)}
            >
              <Icon name="animationblock" />
            </IconButton>
          </Tip>
        )}
      </div>

      {/* The menu is rendered outside of the layer so that its clicks don't select it. */}
      <Menu
        anchorEl={addTimelineBlockMenu.anchorEl}
        open={addTimelineBlockMenu.open}
        onClose={addTimelineBlockMenu.closeMenu}
      >
        {model.availablePropertyNames.map(propertyName => (
          <MenuItem
            key={propertyName}
            onClick={() => {
              addTimelineBlockMenu.closeMenu();
              if (!isActionMode) {
                controller.onAddTimelineBlockClick(layer, propertyName);
              }
            }}
          >
            {getPropertyTitle(propertyName)}
          </MenuItem>
        ))}
      </Menu>

      {/* List the property names that have been animated. */}
      {model.isExpanded && model.existingPropertyNames.length > 0 && (
        <div className="slt-properties">
          {model.existingPropertyNames.map(propertyName => (
            <div className="slt-property fx-row fx-align-start-center" key={propertyName}>
              <span className="slt-property-name">{getPropertyTitle(propertyName)}</span>
              <Tip title="Add another animation" enterDelay={1000} disabled={isActionMode}>
                <IconButton
                  className="slt-property-add-timeline-block-button"
                  disabled={isActionMode}
                  onClick={event => {
                    // Otherwise the workspace would deselect the new block.
                    event.stopPropagation();
                    if (!isActionMode) {
                      controller.onAddTimelineBlockClick(layer, propertyName);
                    }
                  }}
                >
                  <Icon name="add" />
                </IconButton>
              </Tip>
            </div>
          ))}
        </div>
      )}

      {/* List the layer's children if it is expanded. */}
      {model.isExpanded && layer.children.length > 0 && (
        <ul className="slt-children">
          {layer.children.map(child => (
            <li key={child.id} className="slt-layer-container" data-layer-id={child.id}>
              <LayerListTree layer={child} />
            </li>
          ))}
        </ul>
      )}
    </div>
  );
});
