// src/app/components/layertimeline/layerlisttree.component.ts
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  OnInit,
  Output,
} from '@angular/core';
import { ClipPathLayer, GroupLayer, Layer, PathLayer, VectorLayer } from 'app/model/layers';
import { Animation } from 'app/model/timeline';
import { ModelUtil } from 'app/scripts/common';
import { ActionModeService } from 'app/services';
import { State, Store } from 'app/store';
import { getLayerListTreeState } from 'app/store/common/selectors';
import * as _ from 'lodash';
import { Observable } from 'rxjs/Observable';
import { map } from 'rxjs/operators';

@Component({
  selector: 'app-layerlisttree',
  templateUrl: './layerlisttree.component.html',
  styleUrls: ['./layerlisttree.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class LayerListTreeComponent implements OnInit, Callbacks {
  layerModel$: Observable<LayerModel>;

  @Input() layer: Layer;

  // MouseEvents from this layer (or children layers further down the tree)
  // are recursively handled by parent components until they reach
  // the LayerTimelineComponent.
  @Output() layerClick = new EventEmitter<LayerEvent>();
  @Output() layerDoubleClick = new EventEmitter<LayerEvent>();
  @Output() layerMouseDown = new EventEmitter<LayerEvent>();
  @Output() layerToggleExpanded = new EventEmitter<LayerEvent>();
  @Output() layerToggleVisibility = new EventEmitter<LayerEvent>();
  @Output() addTimelineBlockClick = new EventEmitter<TimelineBlockEvent>();
  @Output() convertToClipPathClick = new EventEmitter<LayerEvent>();
  @Output() convertToPathClick = new EventEmitter<LayerEvent>();
  @Output() flattenGroupClick = new EventEmitter<LayerEvent>();

  constructor(
    private readonly store: Store<State>,
    private readonly actionModeService: ActionModeService,
  ) {}

  // @Override
  ngOnInit() {
    this.layerModel$ = this.store.select(getLayerListTreeState).pipe(
      map(
        ({
          animation,
          selectedLayerIds,
          collapsedLayerIds,
          hiddenLayerIds,
          hoveredLayerId,
          isActionMode,
        }) => {
          const isExpandable = this.isLayerExpandable();
          const availablePropertyNames = Array.from(
            ModelUtil.getAvailablePropertyNamesForLayer(this.layer, animation),
          );
          const getExistingPropertyNamesFn = (layerId: string) => {
            return _.keys(ModelUtil.getOrderedBlocksByPropertyByLayer(animation)[layerId]);
          };
          const existingPropertyNames = getExistingPropertyNamesFn(this.layer.id);
          const isClipPathLayer = this.layer instanceof ClipPathLayer;
          const isPathLayer = this.layer instanceof PathLayer;
          const isMergeable =
            this.layer instanceof GroupLayer &&
            this.layer.children.length > 0 &&
            // TODO: allow merging groups w/ existing blocks in some cases?
            existingPropertyNames.length === 0 &&
            this.layer.children.every(l => {
              return (
                l instanceof PathLayer ||
                l instanceof ClipPathLayer ||
                // TODO: allow merging groups into groups w/ existing blocks in some cases?
                getExistingPropertyNamesFn(l.id).length === 0
              );
            });
          return {
            animation,
            isSelected: selectedLayerIds.has(this.layer.id),
            isHovered: hoveredLayerId === this.layer.id,
            isExpandable,
            isExpanded: !collapsedLayerIds.has(this.layer.id),
            isVisible: !hiddenLayerIds.has(this.layer.id),
            availablePropertyNames,
            existingPropertyNames,
            isActionMode,
            isClipPathLayer,
            isPathLayer,
            isMorphableLayer: isClipPathLayer || isPathLayer,
            isMergeable,
          };
        },
      ),
    );
  }

  // @Override
  onLayerClick(event: MouseEvent, layer: Layer) {
    event.stopPropagation();
    if (!this.actionModeService.isActionMode()) {
      this.layerClick.emit({ event, layer });
    }
  }

  // @Override
  onLayerMouseDown(event: MouseEvent, layer: Layer) {
    if (!this.actionModeService.isActionMode()) {
      this.layerMouseDown.emit({ event, layer });
    }
  }

  // @Override
  onLayerToggleExpanded(event: MouseEvent, layer: Layer) {
    event.stopPropagation();
    if (this.isLayerExpandable()) {
      this.layerToggleExpanded.emit({ event, layer });
    }
  }

  // @Override
  onLayerToggleVisibility(event: MouseEvent, layer: Layer) {
    event.stopPropagation();
    if (!this.actionModeService.isActionMode()) {
      this.layerToggleVisibility.emit({ event, layer });
    }
  }

  // @Override
  onAddTimelineBlockClick(event: MouseEvent, layer: Layer, propertyName: string) {
    if (!this.actionModeService.isActionMode()) {
      this.addTimelineBlockClick.emit({ event, layer, propertyName });
    }
  }

  // @Override
  onConvertToClipPathClick(event: MouseEvent, layer: Layer) {
    if (!this.actionModeService.isActionMode()) {
      this.convertToClipPathClick.emit({ event, layer });
    }
  }

  // @Override
  onConvertToPathClick(event: MouseEvent, layer: Layer) {
    if (!this.actionModeService.isActionMode()) {
      this.convertToPathClick.emit({ event, layer });
    }
  }

  // @Override
  onFlattenGroupClick(event: MouseEvent, layer: Layer) {
    if (!this.actionModeService.isActionMode()) {
      this.flattenGroupClick.emit({ event, layer });
    }
  }

  // Used by *ngFor loop.
  trackLayerFn(index: number, layer: Layer) {
    return layer.id;
  }

  private isLayerExpandable() {
    return this.layer instanceof VectorLayer || this.layer instanceof GroupLayer;
  }
}

export interface Callbacks {
  onLayerClick(event: MouseEvent, layer: Layer): void;
  onLayerMouseDown(event: MouseEvent, layer: Layer): void;
  onLayerToggleExpanded(event: MouseEvent, layer: Layer): void;
  onLayerToggleVisibility(event: MouseEvent, layer: Layer): void;
  onAddTimelineBlockClick(event: MouseEvent, layer: Layer, propertyName: string): void;
  onConvertToClipPathClick(event: MouseEvent, layer: Layer): void;
  onConvertToPathClick(event: MouseEvent, layer: Layer): void;
  onFlattenGroupClick(event: MouseEvent, layer: Layer): void;
}

interface LayerEvent {
  readonly event: MouseEvent;
  readonly layer: Layer;
}

interface TimelineBlockEvent {
  readonly event: MouseEvent;
  readonly layer: Layer;
  readonly propertyName: string;
}

interface LayerModel {
  readonly animation: Animation;
  readonly isSelected: boolean;
  readonly isHovered: boolean;
  readonly isExpandable: boolean;
  readonly isExpanded: boolean;
  readonly isVisible: boolean;
  readonly availablePropertyNames: ReadonlyArray<string>;
  readonly existingPropertyNames: ReadonlyArray<string>;
  readonly isActionMode: boolean;
}

<ng-container *ngIf="(this.layerModel$ | async) as model">
  <div class="slt-layer slt-layer-type-{{ this.layer.type }}"
    fxLayout="row"
    fxLayoutAlign="start center"
    [ngClass]="{
      'is-selected': model.isSelected,
      'is-disabled': model.isActionMode,
      'is-hovered': model.isHovered
    }"
    (click)="this.onLayerClick($event, this.layer)"
    (dblclick)="this.onLayerToggleExpanded($event, this.layer)"
    (mousedown)="this.onLayerMouseDown($event, this.layer)">
    <button mat-icon-button
      *ngIf="model.isExpandable"
      (click)="this.onLayerToggleExpanded($event, this.layer)"
      [disabled]="model.isActionMode"
      matTooltip="{{ model.isExpanded ? 'Collapse layer' : 'Expand layer' }}"
      matTooltipPosition="right"
      matTooltipShowDelay="1000">
      <mat-icon>{{ model.isExpanded ? 'expand_more' : 'chevron_right' }}</mat-icon>
    </button>
    <!-- Add extra 20px margin if the expand/collapse icon isn't being displayed -->
    <mat-icon svgIcon="{{ this.layer.type }}"
      [style.margin-left]="model.isExpandable ? '0px' : '20px'">
    </mat-icon>
    <span class="slt-layer-id-text"
      fxFlex>
      {{ this.layer.name }}
    </span>
    <!-- Show overflow options. -->
    <mat-menu #showOverflowOptionsMenu="matMenu">
      <button *ngIf="model.isPathLayer"
        (click)="this.onConvertToClipPathClick($event, layer)"
        mat-menu-item>
        Convert to clip path
      </button>
      <button *ngIf="model.isClipPathLayer"
        (click)="this.onConvertToPathClick($event, layer)"
        mat-menu-item>
        Convert to path
      </button>
      <button *ngIf="model.isMergeable"
        (click)="this.onFlattenGroupClick($event, layer)"
        mat-menu-item>
        Flatten group
      </button>
    </mat-menu>
    <button mat-icon-button
      *ngIf="model.isMorphableLayer || model.isMergeable"
      class="slt-layer-action-button slt-layer-more-actions"
      (click)="$event.stopPropagation()"
      [disabled]="model.isActionMode"
      [matMenuTriggerFor]="showOverflowOptionsMenu">
      <mat-icon>more_vert</mat-icon>
    </button>
    <!-- Visibility toggle. -->
    <button mat-icon-button
      class="slt-layer-action-button slt-layer-visibility-toggle"
      (click)="this.onLayerToggleVisibility($event, this.layer)"
      [disabled]="model.isActionMode"
      matTooltip="{{ model.isVisible ? 'Hide layer' : 'Show layer' }}"
      matTooltipPosition="below"
      matTooltipShowDelay="1000"
      [ngClass]="{'is-checked': model.isVisible}">
      <mat-icon>{{ model.isVisible ? 'visibility' : 'visibility_off' }}</mat-icon>
    </button>
    <!-- Animate layer. -->
    <mat-menu #addTimelineBlockMenu="matMenu">
      <button *ngFor="let propertyName of model.availablePropertyNames"
        (click)="this.onAddTimelineBlockClick($event, layer, propertyName)"
        mat-menu-item>
        {{ propertyName }}
      </button>
    </mat-menu>
    <button mat-icon-button
      *ngIf="model.availablePropertyNames.length > 0"
      class="slt-layer-action-button"
      (click)="$event.stopPropagation()"
      [disabled]="model.isActionMode"
      matTooltip="Animate this layer"
      matTooltipPosition="below"
      matTooltipShowDelay="1000"
      [matMenuTriggerFor]="addTimelineBlockMenu">
      <mat-icon svgIcon="animationblock"></mat-icon>
    </button>
  </div>

  <!-- List the property names that have been animated. -->
  <div class="slt-properties"
    *ngIf="model.isExpanded && model.existingPropertyNames.length > 0">
    <div class="slt-property"
      fxLayout="row"
      fxLayoutAlign="start center"
      *ngFor="let propertyName of model.existingPropertyNames">
      <span class="slt-property-name">{{ propertyName }}</span>
      <button mat-icon-button
        class="slt-property-add-timeline-block-button"
        (click)="this.onAddTimelineBlockClick($event, layer, propertyName)"
        [disabled]="model.isActionMode"
        matTooltip="Add another animation"
        matTooltipPosition="below"
        matTooltipShowDelay="1000">
        <mat-icon>add</mat-icon>
      </button>
    </div>
  </div>

  <!-- List the layer's children if it is expanded. -->
  <ul *ngIf="model.isExpanded && this.layer.children.length > 0"
    class="slt-children">
    <li *ngFor="let child of this.layer.children; trackBy: this.trackLayerFn"
      class="slt-layer-container"
      [attr.data-layer-id]="child.id">
      <app-layerlisttree [layer]="child"
        (layerMouseDown)="this.onLayerMouseDown($event.event, $event.layer)"
        (layerClick)="this.onLayerClick($event.event, $event.layer)"
        (layerToggleExpanded)="this.onLayerToggleExpanded($event.event, $event.layer)"
        (layerToggleVisibility)="this.onLayerToggleVisibility($event.event, $event.layer)"
        (addTimelineBlockClick)="this.onAddTimelineBlockClick($event.event, $event.layer, $event.propertyName)"
        (convertToClipPathClick)="this.onConvertToClipPathClick($event.event, $event.layer)"
        (convertToPathClick)="this.onConvertToPathClick($event.event, $event.layer)"
        (flattenGroupClick)="this.onFlattenGroupClick($event.event, $event.layer)">
      </app-layerlisttree>
    </li>
  </ul>
</ng-container>

// src/app/modules/editor/components/layertimeline/LayerListTree.tsx
import IconButton from '@mui/material/IconButton';
import Menu from '@mui/material/Menu';
import MenuItem from '@mui/material/MenuItem';
import { Tip } from 'app/modules/editor/components/common/Tip';
import { Icon, type IconName } from 'app/modules/editor/components/icons/Icon';
import { useAppSelector } from 'app/modules/editor/hooks/useAppSelector';
import { useMenu } from 'app/modules/editor/hooks/useMenu';
import {
  ClipPathLayer,
  GroupLayer,
  type Layer,
  PathLayer,
  VectorLayer,
} from 'app/modules/editor/model/layers';
import { PathAnimationBlock } from 'app/modules/editor/model/timeline';
import * as ModelUtil from 'app/modules/editor/scripts/common/ModelUtil';
import { getLayerListTreeState } from 'app/modules/editor/store/common/selectors';
import { keys } from 'lodash-es';
import { memo, type MouseEvent, useMemo } from 'react';

import './layerlisttree.scss';
import { useLayerTimelineController } from './LayerTimelineContext';

function buildLayerModel(
  layer: Layer,
  {
    animation,
    selectedLayerIds,
    collapsedLayerIds,
    hiddenLayerIds,
    hoveredLayerId,
    isActionMode,
  }: ReturnType<typeof getLayerListTreeState>,
) {
  const isExpandable = layer instanceof VectorLayer || layer instanceof GroupLayer;
  const availablePropertyNames = Array.from(
    ModelUtil.getAvailablePropertyNamesForLayer(layer, animation),
  );
  const getExistingPropertyNamesFn = (layerId: string) => {
    return keys(ModelUtil.getOrderedBlocksByPropertyByLayer(animation)[layerId]);
  };
  const existingPropertyNames = getExistingPropertyNamesFn(layer.id);
  const canBeConvertedToPath = layer instanceof ClipPathLayer;
  // We can't convert a path into a clip path if it has incompatible animation blocks.
  const canBeConvertedToClipPath =
    layer instanceof PathLayer &&
    // TODO: comparing the sets of all animatable properties for each layer type would be more robust
    !animation.blocks.some(b => !(b instanceof PathAnimationBlock));
  const canBeFlattened =
    layer instanceof GroupLayer &&
    layer.children.length > 0 &&
    // TODO: allow merging groups w/ existing blocks in some cases?
    existingPropertyNames.length === 0 &&
    layer.children.every(l => {
      return (
        l instanceof PathLayer ||
        l instanceof ClipPathLayer ||
        // TODO: allow merging groups into groups w/ existing blocks in some cases?
        getExistingPropertyNamesFn(l.id).length === 0
      );
    });
  return {
    isSelected: selectedLayerIds.has(layer.id),
    isHovered: hoveredLayerId === layer.id,
    isExpandable,
    isExpanded: !collapsedLayerIds.has(layer.id),
    isVisible: !hiddenLayerIds.has(layer.id),
    availablePropertyNames,
    existingPropertyNames,
    isActionMode,
    canBeConvertedToClipPath,
    canBeConvertedToPath,
    canBeFlattened,
  };
}

/**
 * Lists the layer, its animated properties, and (recursively) its children.
 */
export const LayerListTree = memo(function LayerListTree({ layer }: { layer: Layer }) {
  const controller = useLayerTimelineController();
  const layerListTreeState = useAppSelector(getLayerListTreeState);
  const model = useMemo(
    () => buildLayerModel(layer, layerListTreeState),
    [layer, layerListTreeState],
  );
  const overflowMenu = useMenu();
  const addTimelineBlockMenu = useMenu();
  const { isActionMode } = model;

  const onToggleExpanded = (event: MouseEvent) => {
    event.stopPropagation();
    if (model.isExpandable) {
      controller.onLayerToggleExpanded(event.nativeEvent, layer);
    }
  };

  // Stops the click from also selecting the layer.
  const onMenuButtonClick = (openMenu: (event: MouseEvent<HTMLElement>) => void) => {
    return (event: MouseEvent<HTMLElement>) => {
      event.stopPropagation();
      openMenu(event);
    };
  };

  const layerClassNames = [
    'slt-layer',
    `slt-layer-type-${layer.type}`,
    'fx-row',
    'fx-align-start-center',
    model.isSelected && 'is-selected',
    model.isHovered && 'is-hovered',
    isActionMode && 'is-disabled',
  ];

  return (
    <div className="app-layerlisttree">
      <div
        className={layerClassNames.filter(Boolean).join(' ')}
        onClick={event => {
          event.stopPropagation();
          if (!isActionMode) {
            controller.onLayerClick(event.nativeEvent, layer);
          }
        }}
        onDoubleClick={onToggleExpanded}
        onMouseDown={event => {
          if (!isActionMode) {
            controller.onLayerMouseDown(event.nativeEvent, layer);
          }
        }}
      >
        {model.isExpandable && (
          <Tip
            title={model.isExpanded ? 'Collapse layer' : 'Expand layer'}
            placement="right"
            enterDelay={1000}
            disabled={isActionMode}
          >
            <IconButton disabled={isActionMode} onClick={onToggleExpanded}>
              <Icon name={model.isExpanded ? 'expand_more' : 'chevron_right'} />
            </IconButton>
          </Tip>
        )}
        {/* Add an extra 20px margin if the expand/collapse icon isn't being displayed. */}
        <Icon
          className={model.isExpandable ? 'slt-layer-type-icon' : 'slt-layer-type-icon is-indented'}
          name={layer.type as IconName}
        />
        <span className="slt-layer-id-text fx-flex">{layer.name}</span>
        {/* Show overflow options. */}
        {(model.canBeConvertedToClipPath || model.canBeConvertedToPath || model.canBeFlattened) && (
          <IconButton
            className="slt-layer-action-button slt-layer-more-actions"
            disabled={isActionMode}
            onClick={onMenuButtonClick(overflowMenu.openMenu)}
          >
            <Icon name="more_vert" />
          </IconButton>
        )}
        {/* Visibility toggle. */}
        <Tip
          title={model.isVisible ? 'Hide layer' : 'Show layer'}
          enterDelay={1000}
          disabled={isActionMode}
        >
          <IconButton
            className={`slt-layer-action-button slt-layer-visibility-toggle${
              model.isVisible ? ' is-checked' : ''
            }`}
            disabled={isActionMode}
            onClick={event => {
              event.stopPropagation();
              if (!isActionMode) {
                controller.onLayerToggleVisibility(layer);
              }
            }}
          >
            <Icon name={model.isVisible ? 'visibility' : 'visibility_off'} />
          </IconButton>
        </Tip>
        {/* Animate layer. */}
        {model.availablePropertyNames.length > 0 && (
          <Tip title="Animate this layer" enterDelay={1000} disabled={isActionMode}>
            <IconButton
              className="slt-layer-action-button"
              disabled={isActionMode}
              onClick={onMenuButtonClick(addTimelineBlockMenu.openMenu)}
            >
              <Icon name="animationblock" />
            </IconButton>
          </Tip>
        )}
      </div>

      {/* The menus are rendered outside of the layer so that their clicks don't select it. */}
      <Menu
        anchorEl={overflowMenu.anchorEl}
        open={overflowMenu.open}
        onClose={overflowMenu.closeMenu}
      >
        {model.canBeConvertedToClipPath && (
          <MenuItem
            onClick={() => {
              overflowMenu.closeMenu();
              controller.onConvertToClipPathClick(layer);
            }}
          >
            Convert to clip path
          </MenuItem>
        )}
        {model.canBeConvertedToPath && (
          <MenuItem
            onClick={() => {
              overflowMenu.closeMenu();
              controller.onConvertToPathClick(layer);
            }}
          >
            Convert to path
          </MenuItem>
        )}
        {model.canBeFlattened && (
          <MenuItem
            onClick={() => {
              overflowMenu.closeMenu();
              controller.onFlattenGroupClick(layer);
            }}
          >
            Flatten group
          </MenuItem>
        )}
      </Menu>
      <Menu
        anchorEl={addTimelineBlockMenu.anchorEl}
        open={addTimelineBlockMenu.open}
        onClose={addTimelineBlockMenu.closeMenu}
      >
        {model.availablePropertyNames.map(propertyName => (
          <MenuItem
            key={propertyName}
            onClick={() => {
              addTimelineBlockMenu.closeMenu();
              if (!isActionMode) {
                controller.onAddTimelineBlockClick(layer, propertyName);
              }
            }}
          >
            {propertyName}
          </MenuItem>
        ))}
      </Menu>

      {/* List the property names that have been animated. */}
      {model.isExpanded && model.existingPropertyNames.length > 0 && (
        <div className="slt-properties">
          {model.existingPropertyNames.map(propertyName => (
            <div className="slt-property fx-row fx-align-start-center" key={propertyName}>
              <span className="slt-property-name">{propertyName}</span>
              <Tip title="Add another animation" enterDelay={1000} disabled={isActionMode}>
                <IconButton
                  className="slt-property-add-timeline-block-button"
                  disabled={isActionMode}
                  onClick={event => {
                    // Otherwise the workspace would deselect the new block.
                    event.stopPropagation();
                    if (!isActionMode) {
                      controller.onAddTimelineBlockClick(layer, propertyName);
                    }
                  }}
                >
                  <Icon name="add" />
                </IconButton>
              </Tip>
            </div>
          ))}
        </div>
      )}

      {/* List the layer's children if it is expanded. */}
      {model.isExpanded && layer.children.length > 0 && (
        <ul className="slt-children">
          {layer.children.map(child => (
            <li key={child.id} className="slt-layer-container" data-layer-id={child.id}>
              <LayerListTree layer={child} />
            </li>
          ))}
        </ul>
      )}
    </div>
  );
});
