// src/app/modules/editor/components/propertyinput/propertyinput.component.ts
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';
import { ActionMode } from 'app/modules/editor/model/actionmode';
import {
  ClipPathLayer,
  GroupLayer,
  Layer,
  LayerUtil,
  PathLayer,
  VectorLayer,
} from 'app/modules/editor/model/layers';
import { FractionProperty, NameProperty, Option } from 'app/modules/editor/model/properties';
import { Animation, PathAnimationBlock } from 'app/modules/editor/model/timeline';
import { ColorUtil, ModelUtil } from 'app/modules/editor/scripts/common';
import {
  ActionModeService,
  LayerTimelineService,
  PlaybackService,
  ShortcutService,
  ThemeService,
} from 'app/modules/editor/services';
import { State, Store } from 'app/modules/editor/store';
import { getPropertyInputState } from 'app/modules/editor/store/common/selectors';
import { ThemeType } from 'app/modules/editor/store/theme/reducer';
import { SetAnimation } from 'app/modules/editor/store/timeline/actions';
import * as $ from 'jquery';
import * as _ from 'lodash';
import { Observable, combineLatest } from 'rxjs';
import { map } from 'rxjs/operators';

import { InspectedProperty } from './InspectedProperty';

declare const ga: Function;

// TODO: when you enter a 'start time' larger than 'end time', transform 'end time' correctly
@Component({
  selector: 'app-propertyinput',
  templateUrl: './propertyinput.component.html',
  styleUrls: ['./propertyinput.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PropertyInputComponent implements OnInit {
  propertyInputModel$: Observable<PropertyInputModel>;

  // Map used to track user state that has been entered into textfields
  // but may not have been saved in the store.
  private readonly enteredValueMap = new Map<string>();

  themeState$: Observable<{ prevThemeType: ThemeType; currThemeType: ThemeType }>;

  constructor(
    private readonly store: Store<State>,
    private readonly actionModeService: ActionModeService,
    private readonly playbackService: PlaybackService,
    private readonly layerTimelineService: LayerTimelineService,
    readonly themeService: ThemeService,
  ) {}

  ngOnInit() {
    let prevThemeType: ThemeType;
    let currThemeType = this.themeService.getThemeType().themeType;
    this.propertyInputModel$ = this.store.select(getPropertyInputState).pipe(
      map(({ animation, isAnimationSelected, selectedBlockIds, vectorLayer, selectedLayerIds }) => {
        prevThemeType = currThemeType = this.themeService.getThemeType().themeType;
        if (selectedLayerIds.size) {
          return this.buildInspectedLayerProperties(vectorLayer, selectedLayerIds, animation);
        } else if (selectedBlockIds.size) {
          return this.buildInspectedBlockProperties(vectorLayer, animation, selectedBlockIds);
        } else if (isAnimationSelected) {
          return this.buildInspectedAnimationProperties(animation);
        } else {
          return {
            numSelections: 0,
            inspectedProperties: [],
            availablePropertyNames: [],
          } as PropertyInputModel;
        }
      }),
    );
    this.themeState$ = combineLatest(
      this.propertyInputModel$,
      this.themeService.asObservable(),
    ).pipe(
      map(([unused, { themeType }]) => {
        prevThemeType = currThemeType;
        currThemeType = this.themeService.getThemeType().themeType;
        return { prevThemeType, currThemeType };
      }),
    );
  }

  shouldShowStartActionModeButton(pim: PropertyInputModel) {
    return pim.numSelections === 1 && pim.model instanceof PathAnimationBlock;
  }

  shouldDisableStartActionModeButton(pim: PropertyInputModel) {
    if (!this.shouldShowStartActionModeButton(pim)) {
      return false;
    }
    const { fromValue, toValue } = pim.model as PathAnimationBlock;
    return !fromValue || !fromValue.getPathString() || !toValue || !toValue.getPathString();
  }

  onAutoFixPathsClick(pim: PropertyInputModel) {
    this.actionModeService.autoFix();
  }

  onStartActionModeClick() {
    ga('send', 'event', 'Action mode', 'Started');
    this.actionModeService.setActionMode(ActionMode.Selection);
  }

  shouldShowAnimateLayerButton(pim: PropertyInputModel) {
    return (
      pim.availablePropertyNames.length > 0 &&
      pim.numSelections === 1 &&
      (pim.model instanceof VectorLayer ||
        pim.model instanceof GroupLayer ||
        pim.model instanceof ClipPathLayer ||
        pim.model instanceof PathLayer)
    );
  }

  onAnimateLayerClick(layer: Layer, propertyName: string) {
    const clonedValue = layer.inspectableProperties
      .get(propertyName)
      .cloneValue((layer as any)[propertyName]);
    const currentTime = this.playbackService.getCurrentTime();
    this.layerTimelineService.addBlocks([
      {
        layerId: layer.id,
        propertyName,
        fromValue: clonedValue,
        toValue: clonedValue,
        currentTime,
      },
    ]);
  }

  shouldShowInvalidPathAnimationBlockMsg(pim: PropertyInputModel) {
    return (
      pim.numSelections === 1 &&
      pim.model instanceof PathAnimationBlock &&
      !pim.model.isAnimatable()
    );
  }

  isPathBlockFromValueEmpty(block: PathAnimationBlock) {
    return !block.fromValue || !block.fromValue.getPathString();
  }

  isPathBlockToValueEmpty(block: PathAnimationBlock) {
    return !block.toValue || !block.toValue.getPathString();
  }

  onValueEditorKeyDown(event: KeyboardEvent, ip: InspectedProperty<any>) {
    switch (event.keyCode) {
      // Up/down arrow buttons.
      case 38:
      case 40:
        ip.resolveEnteredValue();
        const $target = $(event.target) as JQuery<HTMLInputElement>;
        const numberValue = Number($target.val());
        if (isNaN(numberValue)) {
          break;
        }
        let delta = event.keyCode === 38 ? 1 : -1;

        if (ip.property instanceof FractionProperty) {
          delta *= 0.1;
        }

        if (event.shiftKey) {
          // TODO: make this more obvious somehow
          delta *= 10;
        } else if (ShortcutService.isOsDependentModifierKey(event)) {
          // TODO: make this more obvious somehow
          delta /= 10;
        }

        ip.property.setEditableValue(ip, 'value', Number((numberValue + delta).toFixed(6)));
        setTimeout(() => $target.get(0).select(), 0);
        return false;
    }
    return undefined;
  }

  private buildInspectedLayerProperties(
    vl: VectorLayer,
    selectedLayerIds: ReadonlySet<string>,
    animation: Animation,
  ) {
    const numSelections = selectedLayerIds.size;
    const selectedLayers = Array.from(selectedLayerIds).map(id => vl.findLayerById(id));
    if (numSelections > 1) {
      return {
        numSelections,
        icon: 'collection',
        description: `${numSelections} layers`,
        // TODO: implement batch editting
        inspectedProperties: [],
        availablePropertyNames: [],
      } as PropertyInputModel;
    }
    // Edit a single layer.
    const enteredValueMap = this.enteredValueMap;
    const layer = selectedLayers[0];
    const icon = layer.type;
    const description = layer.name;
    const inspectedProperties: InspectedProperty<any>[] = [];
    layer.inspectableProperties.forEach((property, propertyName) => {
      inspectedProperties.push(
        new InspectedProperty<any>(
          layer,
          property,
          propertyName,
          enteredValueMap,
          value => {
            // TODO: avoid dispatching the action if the properties are equal
            const clonedLayer: any = layer.clone();
            clonedLayer[propertyName] = value;
            this.layerTimelineService.updateLayer(clonedLayer);
          },
          // TODO: return the 'rendered' value if an animation is ongoing? (see AIA)
          undefined,
          enteredValue => {
            if (property instanceof NameProperty) {
              return LayerUtil.getUniqueLayerName([vl], NameProperty.sanitize(enteredValue));
            }
            return enteredValue;
          },
          // TODO: copy AIA conditions to determine whether this should be editable
          undefined,
        ),
      );
    });
    const availablePropertyNames = Array.from(
      ModelUtil.getAvailablePropertyNamesForLayer(layer, animation),
    );
    return {
      model: layer,
      numSelections,
      inspectedProperties,
      icon,
      description,
      availablePropertyNames,
    } as PropertyInputModel;
  }

  private buildInspectedBlockProperties(
    vl: VectorLayer,
    animation: Animation,
    selectedBlockIds: ReadonlySet<string>,
  ) {
    const numSelections = selectedBlockIds.size;
    const selectedBlocks = Array.from(selectedBlockIds).map(id => {
      return _.find(animation.blocks, b => b.id === id);
    });
    if (numSelections > 1) {
      return {
        numSelections,
        icon: 'collection',
        // TODO: implement batch editting
        description: `${numSelections} property animations`,
        inspectedProperties: [],
        availablePropertyNames: [],
      } as PropertyInputModel;
    }
    const enteredValueMap = this.enteredValueMap;
    const block = selectedBlocks[0];
    const icon = 'animationblock';
    const description = block.propertyName;
    const blockLayer = vl.findLayerById(block.layerId);
    const subDescription = `for '${blockLayer.name}'`;
    const inspectedProperties: InspectedProperty<any>[] = [];
    block.inspectableProperties.forEach((property, propertyName) => {
      inspectedProperties.push(
        new InspectedProperty<any>(block, property, propertyName, enteredValueMap, value => {
          // TODO: avoid dispatching the action if the properties are equal
          const clonedBlock: any = block.clone();
          clonedBlock[propertyName] = value;
          this.layerTimelineService.updateBlocks([clonedBlock]);
        }),
      );
    });
    return {
      model: block,
      numSelections,
      inspectedProperties,
      icon,
      description,
      subDescription,
      availablePropertyNames: [],
    } as PropertyInputModel;
  }

  private buildInspectedAnimationProperties(animation: Animation) {
    const store = this.store;
    const enteredValueMap = this.enteredValueMap;
    const icon = 'animation';
    const description = animation.name;
    const inspectedProperties: InspectedProperty<any>[] = [];
    animation.inspectableProperties.forEach((property, propertyName) => {
      inspectedProperties.push(
        new InspectedProperty<any>(
          animation,
          property,
          propertyName,
          enteredValueMap,
          value => {
            // TODO: avoid dispatching the action if the properties are equal
            const clonedAnimation: any = animation.clone();
            clonedAnimation[propertyName] = value;
            store.dispatch(new SetAnimation(clonedAnimation));
          },
          undefined,
          undefined,
          undefined,
        ),
      );
    });
    return {
      model: animation,
      numSelections: 1,
      inspectedProperties,
      icon,
      description,
      availablePropertyNames: [],
    } as PropertyInputModel;
  }

  // Called from the HTML template.
  androidToCssColor(color: string) {
    return ColorUtil.androidToCssHexColor(color);
  }

  trackInspectedPropertyFn(index: number, ip: InspectedProperty<any>) {
    return ip.propertyName;
  }

  trackEnumOptionFn(index: number, option: Option) {
    return option.value;
  }
}

// TODO: use this for batch editing
// function getSharedPropertyNames(items: ReadonlyArray<Inspectable>) {
//   if (!items || !items.length) {
//     return [];
//   }
//   let shared: ReadonlyArray<string>;
//   items.forEach(item => {
//     const names = Array.from(item.inspectableProperties.keys());
//     if (!shared) {
//       shared = names;
//     } else {
//       shared = shared.filter(n => names.includes(n));
//     }
//   });
//   return shared;
// }

interface PropertyInputModel {
  readonly model?: any;
  readonly numSelections: number;
  readonly inspectedProperties: ReadonlyArray<InspectedProperty<any>>;
  // TODO: use a union type here for better type safety?
  readonly icon?: string;
  readonly description?: string;
  readonly subDescription?: string;
  readonly availablePropertyNames: ReadonlyArray<string>;
}

// src/app/modules/editor/components/propertyinput/PropertyInput.tsx
import IconButton from '@mui/material/IconButton';
import Menu from '@mui/material/Menu';
import MenuItem from '@mui/material/MenuItem';
import Tooltip from '@mui/material/Tooltip';
import { Tip } from 'app/modules/editor/components/common/Tip';
import { Icon, type IconName } from 'app/modules/editor/components/icons/Icon';
import { Splitter } from 'app/modules/editor/components/splitter';
import { useEditorStore, useServices } from 'app/modules/editor/context/EditorContext';
import { useAppSelector } from 'app/modules/editor/hooks/useAppSelector';
import { useMenu } from 'app/modules/editor/hooks/useMenu';
import { ActionMode } from 'app/modules/editor/model/actionmode';
import type { Layer } from 'app/modules/editor/model/layers';
import { EnumProperty } from 'app/modules/editor/model/properties';
import type { PathAnimationBlock } from 'app/modules/editor/model/timeline';
import { trackEvent } from 'app/modules/editor/scripts/analytics';
import { ColorUtil } from 'app/modules/editor/scripts/common';
import { ShortcutService } from 'app/modules/editor/services';
import { getPropertyInputState } from 'app/modules/editor/store/common/selectors';
import { type KeyboardEvent, type ReactNode, useMemo, useReducer, useState } from 'react';

import {
  buildPropertyInputModel,
  isPathBlockFromValueEmpty,
  isPathBlockToValueEmpty,
  type PropertyInputModel,
  shouldDisableStartActionModeButton,
  shouldShowAnimateLayerButton,
  shouldShowInvalidPathAnimationBlockMsg,
  shouldShowStartActionModeButton,
} from './buildPropertyInputModel';
import type { InspectedProperty } from './InspectedProperty';
import { getSteppedValue } from './steppedValue';
import './propertyinput.scss';

const TEXT_INPUT_TYPE_NAMES = new Set([
  'NameProperty',
  'PathProperty',
  'ColorProperty',
  'NumberProperty',
  'FractionProperty',
]);

// TODO: when you enter a 'start time' larger than 'end time', transform 'end time' correctly
export function PropertyInput() {
  const store = useEditorStore();
  const { actionModeService, layerTimelineService, playbackService } = useServices();
  const propertyInputState = useAppSelector(getPropertyInputState);
  // Tracks values that have been entered into text fields but may not have been saved.
  const [enteredValueMap] = useState(() => new Map<string, any>());
  // Entering an invalid value doesn't change the store, so re-render to show it anyway.
  const [, forceUpdate] = useReducer((x: number) => x + 1, 0);

  const model = useMemo(
    () =>
      buildPropertyInputModel({ store, layerTimelineService, enteredValueMap }, propertyInputState),
    [store, layerTimelineService, enteredValueMap, propertyInputState],
  );

  const onAnimateLayerClick = (layer: Layer, propertyName: string) => {
    const property = layer.inspectableProperties.get(propertyName);
    if (!property) {
      return;
    }
    const clonedValue = property.cloneValue((layer as any)[propertyName]);
    const currentTime = playbackService.getCurrentTime();
    layerTimelineService.addBlocks([
      {
        layerId: layer.id,
        propertyName,
        fromValue: clonedValue,
        toValue: clonedValue,
        currentTime,
      },
    ]);
  };

  const onValueEditorKeyDown = (
    event: KeyboardEvent<HTMLInputElement>,
    ip: InspectedProperty<any>,
  ) => {
    // Up/down arrow buttons.
    if (event.keyCode !== 38 && event.keyCode !== 40) {
      return;
    }
    ip.resolveEnteredValue();
    const target = event.currentTarget;
    const value = getSteppedValue(ip.property, target.value, {
      up: event.keyCode === 38,
      shiftKey: event.shiftKey,
      modifierKey: ShortcutService.isOsDependentModifierKey(event),
    });
    if (value === undefined) {
      forceUpdate();
      return;
    }
    ip.property.setEditableValue(ip, 'value', value);
    forceUpdate();
    setTimeout(() => target.select(), 0);
    event.preventDefault();
    event.stopPropagation();
  };

  return (
    // Clicks shouldn't clear the current selection.
    <div className="app-propertyinput fx-column" onClick={event => event.stopPropagation()}>
      <div className="property-input mat-elevation-z4 ss-theme-transition fx-column fx-flex">
        <Splitter persistId="property-inspector" edge="left" min={200} />
        {model.numSelections === 0 ? (
          <div className="spi-empty fx-flex">Select something to edit its properties</div>
        ) : (
          <div className="spi-content fx-column fx-flex">
            <PropertyInputHeader
              model={model}
              onAnimateLayerClick={onAnimateLayerClick}
              onStartActionModeClick={() => {
                trackEvent('action_mode_start');
                actionModeService.setActionMode(ActionMode.Selection);
              }}
            />
            <div className="spi-body fx-column fx-flex">
              {!model.inspectedProperties.length && (
                <div className="spi-empty fx-flex">No shared properties to view or edit</div>
              )}
              {model.inspectedProperties.map(ip => (
                <div className="spi-property" key={ip.propertyName}>
                  <div className="spi-property-name">{ip.propertyName}</div>
                  <div className="spi-property-value fx-row">
                    {ip.typeName === 'ColorProperty' && (
                      <div
                        className="spi-property-color-preview"
                        style={{ backgroundColor: ColorUtil.androidToCssHexColor(ip.value) }}
                      />
                    )}
                    {!ip.isEditable() && (
                      // Only show text if the property isn't inspectable.
                      <span className="spi-property-value-static fx-flex">
                        {ip.getDisplayValue()}
                      </span>
                    )}
                    {ip.isEditable() && (
                      <div className="spi-property-value-editor fx-column fx-flex">
                        {TEXT_INPUT_TYPE_NAMES.has(ip.typeName) && (
                          <input
                            className={
                              ip.typeName === 'PathProperty' &&
                              shouldShowInvalidPathAnimationBlockMsg(model)
                                ? 'has-input-error'
                                : undefined
                            }
                            name={ip.propertyName}
                            value={ip.editableValue ?? ''}
                            onChange={event => {
                              ip.editableValue = event.target.value;
                              forceUpdate();
                            }}
                            onKeyDown={event => onValueEditorKeyDown(event, ip)}
                            onBlur={() => {
                              ip.resolveEnteredValue();
                              forceUpdate();
                            }}
                          />
                        )}
                        {ip.typeName === 'EnumProperty' && <EnumPropertyEditor ip={ip} />}
                      </div>
                    )}
                  </div>
                </div>
              ))}
              {shouldShowInvalidPathAnimationBlockMsg(model) && (
                <InvalidPathAnimationBlockMessage
                  block={model.model}
                  onAutoFixClick={() => actionModeService.autoFix()}
                />
              )}
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

function PropertyInputHeader({
  model,
  onAnimateLayerClick,
  onStartActionModeClick,
}: {
  model: PropertyInputModel;
  onAnimateLayerClick: (layer: Layer, propertyName: string) => void;
  onStartActionModeClick: () => void;
}) {
  const addTimelineBlockMenu = useMenu();
  const isStartActionModeDisabled = shouldDisableStartActionModeButton(model);
  return (
    <div className="spi-header mat-elevation-z2 ss-theme-transition fx-align-center fx-flex-none">
      <Icon className="spi-selection-icon" name={model.icon as IconName} />
      <div className="spi-selection-description-container fx-column fx-flex">
        <span className="spi-selection-description">{model.description}</span>
        <span className="spi-selection-sub-description">{model.subDescription}</span>
      </div>
      {shouldShowAnimateLayerButton(model) && (
        <>
          <Tooltip title="Animate this layer" placement="left">
            <IconButton
              className="spi-secondary-icon"
              aria-label="Animate this layer"
              onClick={addTimelineBlockMenu.openMenu}
            >
              <Icon name="animationblock" />
            </IconButton>
          </Tooltip>
          <Menu
            anchorEl={addTimelineBlockMenu.anchorEl}
            open={addTimelineBlockMenu.open}
            onClose={addTimelineBlockMenu.closeMenu}
          >
            {model.availablePropertyNames.map(propertyName => (
              <MenuItem
                key={propertyName}
                onClick={() => {
                  addTimelineBlockMenu.closeMenu();
                  onAnimateLayerClick(model.model, propertyName);
                }}
              >
                {propertyName}
              </MenuItem>
            ))}
          </Menu>
        </>
      )}
      {shouldShowStartActionModeButton(model) && (
        <Tip
          title="Edit path morphing animation"
          placement="left"
          disabled={isStartActionModeDisabled}
        >
          <IconButton
            className="spi-secondary-icon"
            aria-label="Edit path morphing animation"
            disabled={isStartActionModeDisabled}
            onClick={onStartActionModeClick}
          >
            <Icon name="edit" />
          </IconButton>
        </Tip>
      )}
    </div>
  );
}

function EnumPropertyEditor({ ip }: { ip: InspectedProperty<any> }) {
  const enumMenu = useMenu();
  const { options } = ip.property as EnumProperty;
  return (
    <>
      <button className="spi-property-value-menu-target" onClick={enumMenu.openMenu}>
        <span className="spi-property-value-menu-current-value">{ip.getDisplayValue()}</span>
        <Icon className="spi-property-value-menu-arrow" name="arrow_drop_down" />
      </button>
      <Menu anchorEl={enumMenu.anchorEl} open={enumMenu.open} onClose={enumMenu.closeMenu}>
        {options.map(option => (
          <MenuItem
            key={option.value}
            onClick={() => {
              enumMenu.closeMenu();
              ip.value = option.value;
            }}
          >
            {option.label}
          </MenuItem>
        ))}
      </Menu>
    </>
  );
}

function InvalidPathAnimationBlockMessage({
  block,
  onAutoFixClick,
}: {
  block: PathAnimationBlock;
  onAutoFixClick: () => void;
}) {
  const isFromValueEmpty = isPathBlockFromValueEmpty(block);
  const isToValueEmpty = isPathBlockToValueEmpty(block);
  let message: ReactNode;
  if (isFromValueEmpty && !isToValueEmpty) {
    message = (
      <>
        <i>fromValue</i> must not be empty
      </>
    );
  } else if (!isFromValueEmpty && isToValueEmpty) {
    message = (
      <>
        <i>toValue</i> must not be empty
      </>
    );
  } else if (isFromValueEmpty && isToValueEmpty) {
    message = (
      <>
        <i>fromValue</i> and <i>toValue</i> must not be empty
      </>
    );
  } else {
    message = (
      <>
        Paths are incompatible. <i>Auto fix</i> or click the <i>edit path morphing animation</i>{' '}
        button above.
      </>
    );
  }
  return (
    <div className="alert alert-danger fx-row">
      <span className="paths-incompatible-text">{message}</span>
      {!isFromValueEmpty && !isToValueEmpty && (
        <Tooltip title="Auto fix">
          <IconButton className="auto-fix-button" aria-label="Auto fix" onClick={onAutoFixClick}>
            <Icon name="autofix" />
          </IconButton>
        </Tooltip>
      )}
    </div>
  );
}
