// src/app/pages/editor/components/playback/playback.component.ts
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';
import { PlaybackService } from 'app/pages/editor/services';
import { State, Store } from 'app/pages/editor/store';
import { getPlaybackState } from 'app/pages/editor/store/playback/selectors';
import { Observable } from 'rxjs';

@Component({
  selector: 'app-playback',
  templateUrl: './playback.component.html',
  styleUrls: ['./playback.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PlaybackComponent implements OnInit {
  playbackModel$: Observable<PlaybackModel>;

  constructor(
    private readonly store: Store<State>,
    private readonly playbackService: PlaybackService,
  ) {}

  ngOnInit() {
    this.playbackModel$ = this.store.select(getPlaybackState);
  }

  isSlowMotionClick(event: MouseEvent) {
    event.stopPropagation();
    this.playbackService.toggleIsSlowMotion();
  }

  rewindClick(event: MouseEvent) {
    event.stopPropagation();
    this.playbackService.rewind();
  }

  playPauseButtonClick(event: MouseEvent) {
    event.stopPropagation();
    this.playbackService.toggleIsPlaying();
  }

  fastForwardClick(event: MouseEvent) {
    event.stopPropagation();
    this.playbackService.fastForward();
  }

  isRepeatingClick(event: MouseEvent) {
    event.stopPropagation();
    this.playbackService.toggleIsRepeating();
  }
}

interface PlaybackModel {
  readonly isSlowMotion: boolean;
  readonly isPlaying: boolean;
  readonly isRepeating: boolean;
}

<div *ngIf="(this.playbackModel$ | async) as model"
  class="playback"
  fxLayout="row"
  fxLayoutAlign="center center">
  <span fxFlex></span>
  <button class="slow-motion-button"
    mat-icon-button
    matTooltip="Slow motion (S)"
    matTooltipPosition="below"
    matTooltipShowDelay="500"
    (click)="this.isSlowMotionClick($event)">
    <mat-icon [class.activated]="model.isSlowMotion">slow_motion_video</mat-icon>
  </button>
  <button mat-icon-button
    matTooltip="Rewind (Left)"
    matTooltipPosition="below"
    matTooltipShowDelay="500"
    (click)="this.rewindClick($event)">
    <mat-icon>skip_previous</mat-icon>
  </button>
  <button mat-mini-fab
    matTooltip="{{ (model.isPlaying) ? 'Pause' : 'Play' }} (Spacebar)"
    matTooltipPosition="below"
    matTooltipShowDelay="500"
    (click)="this.playPauseButtonClick($event)">
    <div
      class="play-pause-icon"
      [ngClass]="{
        'can-animate': true,
        'is-playing': model.isPlaying
      }">
    </div>
  </button>
  <button mat-icon-button
    matTooltip="Fast forward (Right)"
    matTooltipPosition="below"
    matTooltipShowDelay="500"
    (click)="this.fastForwardClick($event)">
    <mat-icon>skip_next</mat-icon>
  </button>
  <button class="repeating-button"
    mat-icon-button
    matTooltip="Repeat (R)"
    matTooltipPosition="below"
    matTooltipShowDelay="500"
    (click)="this.isRepeatingClick($event)">
    <mat-icon [class.activated]="model.isRepeating">repeat</mat-icon>
  </button>
  <span fxFlex></span>
</div>

// src/app/modules/editor/components/playback/Playback.tsx
import Fab from '@mui/material/Fab';
import IconButton from '@mui/material/IconButton';
import Tooltip from '@mui/material/Tooltip';
import { Icon } from 'app/modules/editor/components/icons/Icon';
import { useServices } from 'app/modules/editor/context/EditorContext';
import { useAppSelector } from 'app/modules/editor/hooks/useAppSelector';
import { getPlaybackControlsState } from 'app/modules/editor/store/playback/selectors';
import type { MouseEvent } from 'react';

import './playback.scss';

export function Playback() {
  const { playbackService } = useServices();
  const { isSlowMotion, isPlaying, isRepeating } = useAppSelector(getPlaybackControlsState);

  const onClick = (fn: () => void) => (event: MouseEvent) => {
    event.stopPropagation();
    fn();
  };

  return (
    <div className="playback fx-row fx-align-center">
      <span className="fx-flex" />
      <Tooltip title="Slow motion (S)">
        <IconButton
          className="slow-motion-button"
          onClick={onClick(() => playbackService.toggleIsSlowMotion())}
        >
          <Icon name="slow_motion_video" className={isSlowMotion ? 'activated' : undefined} />
        </IconButton>
      </Tooltip>
      <Tooltip title="Rewind (Left)">
        <IconButton onClick={onClick(() => playbackService.rewind())}>
          <Icon name="skip_previous" />
        </IconButton>
      </Tooltip>
      <Tooltip title={`${isPlaying ? 'Pause' : 'Play'} (Spacebar)`}>
        <Fab
          size="small"
          color="secondary"
          onClick={onClick(() => playbackService.toggleIsPlaying())}
        >
          <div className={`play-pause-icon can-animate${isPlaying ? ' is-playing' : ''}`} />
        </Fab>
      </Tooltip>
      <Tooltip title="Fast forward (Right)">
        <IconButton onClick={onClick(() => playbackService.fastForward())}>
          <Icon name="skip_next" />
        </IconButton>
      </Tooltip>
      <Tooltip title="Repeat (R)">
        <IconButton
          className="repeating-button"
          onClick={onClick(() => playbackService.toggleIsRepeating())}
        >
          <Icon name="repeat" className={isRepeating ? 'activated' : undefined} />
        </IconButton>
      </Tooltip>
      <span className="fx-flex" />
    </div>
  );
}
