// src/app/modules/editor/components/playback/Playback.tsx
import Fab from '@mui/material/Fab';
import IconButton from '@mui/material/IconButton';
import Tooltip from '@mui/material/Tooltip';
import { Icon } from 'app/modules/editor/components/icons/Icon';
import { useServices } from 'app/modules/editor/context/EditorContext';
import { useAppSelector } from 'app/modules/editor/hooks/useAppSelector';
import { getPlaybackControlsState } from 'app/modules/editor/store/playback/selectors';
import type { MouseEvent } from 'react';

import './playback.scss';

export function Playback() {
  const { playbackService } = useServices();
  const { isSlowMotion, isPlaying, isRepeating } = useAppSelector(getPlaybackControlsState);

  const onClick = (fn: () => void) => (event: MouseEvent) => {
    event.stopPropagation();
    fn();
  };

  return (
    <div className="playback fx-row fx-align-center">
      <span className="fx-flex" />
      <Tooltip title="Slow motion (S)">
        <IconButton
          className="slow-motion-button"
          onClick={onClick(() => playbackService.toggleIsSlowMotion())}
        >
          <Icon name="slow_motion_video" className={isSlowMotion ? 'activated' : undefined} />
        </IconButton>
      </Tooltip>
      <Tooltip title="Rewind (Left)">
        <IconButton onClick={onClick(() => playbackService.rewind())}>
          <Icon name="skip_previous" />
        </IconButton>
      </Tooltip>
      <Tooltip title={`${isPlaying ? 'Pause' : 'Play'} (Spacebar)`}>
        <Fab
          size="small"
          color="secondary"
          onClick={onClick(() => playbackService.toggleIsPlaying())}
        >
          <div className={`play-pause-icon can-animate${isPlaying ? ' is-playing' : ''}`} />
        </Fab>
      </Tooltip>
      <Tooltip title="Fast forward (Right)">
        <IconButton onClick={onClick(() => playbackService.fastForward())}>
          <Icon name="skip_next" />
        </IconButton>
      </Tooltip>
      <Tooltip title="Repeat (R)">
        <IconButton
          className="repeating-button"
          onClick={onClick(() => playbackService.toggleIsRepeating())}
        >
          <Icon name="repeat" className={isRepeating ? 'activated' : undefined} />
        </IconButton>
      </Tooltip>
      <span className="fx-flex" />
    </div>
  );
}

// src/app/playback/playback.component.ts
import { AnimatorService } from '../animator';
import { State, Store } from '../store';
import { getPlaybackState } from '../store/playback/selectors';
import { ChangeDetectionStrategy, Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs/Observable';

@Component({
  selector: 'app-playback',
  templateUrl: './playback.component.html',
  styleUrls: ['./playback.component.scss'],
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class PlaybackComponent implements OnInit {

  playbackModel$: Observable<PlaybackModel>;

  constructor(
    private readonly store: Store<State>,
    private readonly animatorService: AnimatorService,
  ) { }

  ngOnInit() {
    this.playbackModel$ = this.store.select(getPlaybackState);
  }

  isSlowMotionClick() {
    this.animatorService.toggleIsSlowMotion();
  }

  playPauseButtonClick() {
    this.animatorService.toggleIsPlaying();
  }

  rewindClick() {
    this.animatorService.rewind();
  }

  fastForwardClick() {
    this.animatorService.fastForward();
  }

  isRepeatingClick() {
    this.animatorService.toggleIsRepeating();
  }
}

interface PlaybackModel {
  readonly isSlowMotion: boolean;
  readonly isPlaying: boolean;
  readonly isRepeating: boolean;
}

<div *ngIf="(playbackModel$ | async) as model"
  fxLayout="row"
  fxLayoutAlight="center center">
  <span fxFlex></span>
  <button md-icon-button
    mdTooltip="Slow motion (T)"
    mdTooltipPosition="below"
    mdTooltipShowDelay="300"
    (click)="this.isSlowMotionClick()">
    <md-icon [class.activated]="model.isSlowMotion">slow_motion_video</md-icon>
  </button>
  <button md-icon-button
    mdTooltip="Rewind (Left)"
    mdTooltipPosition="below"
    mdTooltipShowDelay="300"
    (click)="this.rewindClick()">
    <md-icon>skip_previous</md-icon>
  </button>
  <button md-mini-fab
    mdTooltip="{{ (model.isPlaying) ? 'Pause' : 'Play' }} (Spacebar)"
    mdTooltipPosition="below"
    mdTooltipShowDelay="300"
    (click)="this.playPauseButtonClick()">
    <div
      class="play-pause-icon"
      [ngClass]="{
        'can-animate': true,
        'is-playing': model.isPlaying
      }">
    </div>
    <!--<md-icon *ngIf="(morphStatusObservable | async) !== MORPH_MORPHABLE">play_arrow</md-icon>-->
  </button>
  <button md-icon-button
    mdTooltip="Fast forward (Right)"
    mdTooltipPosition="below"
    mdTooltipShowDelay="300"
    (click)="this.fastForwardClick()">
    <md-icon>skip_next</md-icon>
  </button>
  <button md-icon-button
    mdTooltip="Repeat (R)"
    mdTooltipPosition="below"
    mdTooltipShowDelay="300"
    (click)="this.isRepeatingClick(!model.isRepeating)">
    <md-icon [class.activated]="model.isRepeating">repeat</md-icon>
  </button>
  <span fxFlex></span>
</div>
